package approutegen

import (
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	frameworkrouter "github.com/RevoTale/no-js/framework/router"
	"github.com/RevoTale/no-js/internal/bundler/clientassets"
	"github.com/RevoTale/no-js/internal/bundler/viewcontract"
	"github.com/RevoTale/no-js/internal/projectlayout"
)

var pageViewTypePattern = regexp.MustCompile(`templ\s+Page\s*\(\s*[A-Za-z_][A-Za-z0-9_]*\s+([A-Za-z0-9_.]+)\s*\)`)
var rootTemplateSignaturePattern = regexp.MustCompile(
	`templ\s+RootLayout\s*\(\s*meta\s+metagen\.Metadata\s*,\s*locale\s+string\s*,\s*child\s+templ\.Component\s*\)`,
)
var layoutSignaturePattern = regexp.MustCompile(`(?s)templ\s+Layout\s*\(\s*(.*?)\s*\)`)
var defaultSignaturePattern = regexp.MustCompile(
	`templ\s+Default\s*\(\s*[A-Za-z_][A-Za-z0-9_]*\s+([A-Za-z0-9_.]+)\s*\)`,
)
var notFoundSignaturePattern = regexp.MustCompile(
	`templ\s+NotFound\s*\(\s*[A-Za-z_][A-Za-z0-9_]*\s+([A-Za-z0-9_.]+)\s*,\s*path\s+string\s*\)`,
)
var htmlTagPattern = regexp.MustCompile(`(?i)<\s*html(?:\s|>)`)
var headTagPattern = regexp.MustCompile(`(?i)<\s*head(?:\s|>)`)
var bodyTagPattern = regexp.MustCompile(`(?i)<\s*body(?:\s|>)`)

type templateKind string

const (
	pageTemplate     templateKind = "page"
	layoutTemplate   templateKind = "layout"
	defaultTemplate  templateKind = "default"
	notFoundTemplate templateKind = "not_found"
	errorTemplate    templateKind = "error"
	rootTemplate     templateKind = "root"
)

const (
	generatedResolverFileName = "generated.go"
	generatedGoHeader         = "// Code generated by cmd/approutegen. DO NOT EDIT."
	generatedTemplHeader      = "// Code generated by cmd/approutegen from web/routes. DO NOT EDIT."
	frameworkModulePath       = "github.com/RevoTale/no-js"
	viewPackageName           = "view"
)

type routeSegment struct {
	Kind frameworkrouter.SegmentKind
	Name string
}

func (s routeSegment) IsParam() bool {
	switch s.Kind {
	case frameworkrouter.SegmentDynamic, frameworkrouter.SegmentCatchAll, frameworkrouter.SegmentOptionalCatchAll:
		return true
	default:
		return false
	}
}

func (s routeSegment) IsSlot() bool {
	return s.Kind == frameworkrouter.SegmentSlot
}

func (s routeSegment) IsGroup() bool {
	return s.Kind == frameworkrouter.SegmentGroup
}

func (s routeSegment) ContributesToPublicPath() bool {
	return !s.IsSlot() && !s.IsGroup()
}

func (s routeSegment) RoutePart() string {
	switch s.Kind {
	case frameworkrouter.SegmentDynamic:
		return "_param__" + s.Name
	case frameworkrouter.SegmentCatchAll:
		return "_catchall__" + s.Name
	case frameworkrouter.SegmentOptionalCatchAll:
		return "_optional_catchall__" + s.Name
	case frameworkrouter.SegmentGroup:
		return "_group__" + s.Name
	case frameworkrouter.SegmentSlot:
		return "_slot__" + s.Name
	}
	return s.Name
}

func (s routeSegment) PublicPart() string {
	if !s.ContributesToPublicPath() {
		return ""
	}
	return s.RoutePart()
}

func (s routeSegment) SafePart() string {
	switch s.Kind {
	case frameworkrouter.SegmentDynamic:
		return "param_" + strings.ToLower(s.Name)
	case frameworkrouter.SegmentCatchAll:
		return "catch_all_" + strings.ToLower(s.Name)
	case frameworkrouter.SegmentOptionalCatchAll:
		return "optional_catch_all_" + strings.ToLower(s.Name)
	case frameworkrouter.SegmentGroup:
		return "group_" + safeIdentifier(s.Name)
	case frameworkrouter.SegmentSlot:
		return "slot_" + safeIdentifier(s.Name)
	default:
		return safeIdentifier(s.Name)
	}
}

func (s routeSegment) PatternKeyPart() string {
	switch s.Kind {
	case frameworkrouter.SegmentStatic:
		return s.Name
	case frameworkrouter.SegmentDynamic:
		return ":"
	case frameworkrouter.SegmentCatchAll:
		return "*"
	case frameworkrouter.SegmentOptionalCatchAll:
		return "**"
	default:
		return ""
	}
}

type routeNamespaceKind string

const (
	namespaceMain routeNamespaceKind = "main"
	namespaceSlot routeNamespaceKind = "slot"
)

type sourcePackageDef struct {
	InternalRouteID string
	PublicRouteID   string
	RouteName       string
	ParamsTypeName  string
	Params          []routeParamDef
	ModuleName      string
	Package         string
	SourceDir       string
	Files           []string
}

type methodRouteDef struct {
	InternalRouteID string
	PublicRouteID   string
	Segments        []routeSegment
	PublicSegments  []routeSegment
	RouteName       string
	ParamsTypeName  string
	Params          []routeParamDef
	PackageModule   string
	PackageAlias    string
	Methods         []string
	SourcePath      string
}

type slotDef struct {
	Name         string
	RootInternal string
	Default      *templateDef
	Pages        []routeMeta
	Layouts      map[string]templateDef
}

func newRouteSegment(segment frameworkrouter.Segment) routeSegment {
	return routeSegment{
		Kind: segment.Kind,
		Name: segment.Name,
	}
}

type templateDef struct {
	Kind               templateKind
	RouteID            string
	InternalRouteID    string
	PublicRouteID      string
	SourcePath         string
	Segments           []routeSegment
	PublicSegments     []routeSegment
	RelativeSegments   []routeSegment
	Namespace          routeNamespaceKind
	SlotName           string
	SlotOwnerRouteID   string
	SlotRootInternalID string
	ModuleName         string
	Package            string
	OutputDir          string
	OutputFile         string
	ModelType          string
}

type routeParamDef struct {
	Name      string
	FieldName string
	Type      string
}

type routeMeta struct {
	RouteID            string
	InternalRouteID    string
	PublicRouteID      string
	Segments           []routeSegment
	PublicSegments     []routeSegment
	RelativeSegments   []routeSegment
	Namespace          routeNamespaceKind
	SlotName           string
	SlotOwnerRouteID   string
	SlotRootInternalID string
	RouteName          string
	ParamsTypeName     string
	Params             []routeParamDef
	Page               templateDef
	PageViewType       string
}

type routeContractDef struct {
	RouteID         string
	InternalRouteID string
	PublicRouteID   string
	RouteName       string
	ParamsTypeName  string
	Params          []routeParamDef
}

type routeFiles struct {
	Templates      []templateDef
	Pages          []templateDef
	SlotPages      []templateDef
	Layouts        map[string]templateDef
	SlotLayouts    map[string]templateDef
	Defaults       map[string]templateDef
	NotFounds      map[string]templateDef
	Root           templateDef
	Discovery      discoveryConventions
	MethodRoutes   []methodRouteDef
	SourcePackages []sourcePackageDef
	SlotOwners     map[string][]slotDef
	LayoutSlots    map[string][]string
}

type parsedRouteDir struct {
	SourceDir        string
	Segments         []routeSegment
	PublicSegments   []routeSegment
	RelativeSegments []routeSegment
	Namespace        routeNamespaceKind
	SlotName         string
	SlotOwnerRouteID string
	SlotRootInternal string
	InternalRouteID  string
	PublicRouteID    string
}

type feedConvention struct {
	InternalRouteID string
	RouteID         string
	Segments        []routeSegment
	SourcePath      string
	ImportAlias     string
	PackageModule   string
}

type sitemapConvention struct {
	InternalRouteID     string
	RouteID             string
	Segments            []routeSegment
	SourcePath          string
	ImportAlias         string
	PackageModule       string
	HasSitemap          bool
	HasGenerateSitemaps bool
	HasSitemapChunk     bool
}

type discoveryConventions struct {
	RobotsFile string
	HasRobots  bool
	Sitemaps   []sitemapConvention
	Feeds      []feedConvention
}

type Config struct {
	Layout projectlayout.ProjectLayout
}

func Run(cfg Config) error {
	paths := cfg.Layout
	if strings.TrimSpace(paths.RoutesDir) == "" {
		return errors.New("project layout routes dir is required")
	}
	if strings.TrimSpace(paths.GeneratedDir) == "" {
		return errors.New("project layout generated dir is required")
	}
	if strings.TrimSpace(paths.ResolversDir) == "" {
		return errors.New("project layout resolvers dir is required")
	}
	if strings.TrimSpace(paths.ViewDir) == "" {
		return errors.New("project layout view dir is required")
	}

	routes, err := discoverRouteFiles(paths.RoutesDir, paths.GeneratedDir)
	if err != nil {
		return err
	}
	if len(routes.Pages) == 0 && len(routes.MethodRoutes) == 0 {
		return errors.New("no page.templ or route.go files found in web/routes")
	}
	if routes.Root.SourcePath == "" {
		return errors.New("root template is required: web/routes/root.templ")
	}
	if _, ok := routes.NotFounds[""]; !ok {
		return errors.New("root 404 template is required: web/routes/404.templ")
	}
	if err := inspectRouteTemplateModels(&routes); err != nil {
		return err
	}
	if err := validateRootTemplateSignature(routes.Root.SourcePath); err != nil {
		return err
	}
	for _, tpl := range routes.Templates {
		if tpl.Kind == rootTemplate {
			continue
		}
		if err := validateNoDocumentTags(tpl.SourcePath); err != nil {
			return err
		}
	}
	if err := validateDiscoveryConventions(paths, &routes.Discovery); err != nil {
		return err
	}
	viewHooks, err := viewcontract.Inspect(paths.ViewDir)
	if err != nil {
		return fmt.Errorf("inspect view contract: %w", err)
	}

	metas, err := buildRouteMetas(routes.Pages, paths)
	if err != nil {
		return err
	}
	slotMetas, err := buildRouteMetas(routes.SlotPages, paths)
	if err != nil {
		return err
	}
	if err := validateMethodRoutes(paths, routes.MethodRoutes); err != nil {
		return err
	}
	slotOwners := buildSlotOwners(slotMetas, routes.SlotLayouts, routes.Defaults)

	clientAssetPlan, err := clientassets.Generate(clientassets.Config{
		Layout: paths,
		Routes: clientAssetRouteSpecs(routes.Root, metas, routes.Layouts, slotOwners),
	})
	if err != nil {
		return fmt.Errorf("generate client asset helpers: %w", err)
	}

	if err := os.RemoveAll(paths.GeneratedDir); err != nil {
		return fmt.Errorf("clear generated output: %w", err)
	}
	if err := os.MkdirAll(paths.GeneratedDir, 0o755); err != nil {
		return fmt.Errorf("create generated output root: %w", err)
	}

	for _, tpl := range routes.Templates {
		if err := writeTemplCopy(tpl); err != nil {
			return err
		}
		if err := writeClientAssetHelperCopies(tpl); err != nil {
			return err
		}
	}
	for _, sourcePkg := range routes.SourcePackages {
		if err := writeSourcePackageCopy(sourcePkg, paths.GeneratedDir); err != nil {
			return err
		}
	}

	resolversSource, err := generateResolverNamespaceSource(
		paths,
		metas,
		slotMetas,
		routes.Layouts,
		routes.SlotLayouts,
		routes.Defaults,
		routes.NotFounds,
	)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(paths.ResolversDir, 0o755); err != nil {
		return fmt.Errorf("create resolver namespace root %q: %w", paths.ResolversDir, err)
	}
	resolverFilePath := filepath.Join(paths.ResolversDir, generatedResolverFileName)
	if err := os.WriteFile(resolverFilePath, resolversSource, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", generatedResolverFileName, err)
	}

	registrySource, err := generateRegistrySource(
		paths,
		viewHooks,
		metas,
		slotMetas,
		slotOwners,
		routes.MethodRoutes,
		routes.Root,
		routes.Layouts,
		routes.NotFounds,
		clientAssetPlan,
	)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(paths.GeneratedDir, "registry_gen.go"), registrySource, 0o644); err != nil {
		return fmt.Errorf("write registry_gen.go: %w", err)
	}
	discoverySource, err := generateDiscoverySource(paths, routes.Discovery)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(paths.GeneratedDir, "discovery_gen.go"), discoverySource, 0o644); err != nil {
		return fmt.Errorf("write discovery_gen.go: %w", err)
	}
	bundleSource, err := generateBundleSource(paths, viewHooks)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(paths.GeneratedDir, "bundle_gen.go"), bundleSource, 0o644); err != nil {
		return fmt.Errorf("write bundle_gen.go: %w", err)
	}

	return nil
}

func appImportPath(modulePath string, relativePath string) string {
	trimmedModulePath := strings.TrimSpace(modulePath)
	trimmedRelativePath := strings.Trim(strings.TrimSpace(relativePath), "/")
	if trimmedRelativePath == "" {
		return trimmedModulePath
	}
	return path.Join(trimmedModulePath, trimmedRelativePath)
}

func resolversImportPath(paths projectlayout.ProjectLayout) string {
	relativePath := strings.TrimSpace(paths.ResolversImport)
	if relativePath == "" {
		relativePath = "web/resolvers"
	}
	return appImportPath(paths.AppModulePath, relativePath)
}

func generatedI18nMessagesImportPath(paths projectlayout.ProjectLayout) string {
	relativePath := strings.TrimSpace(paths.GeneratedImport)
	if relativePath == "" {
		relativePath = "web/generated"
	}
	return appImportPath(paths.AppModulePath, path.Join(relativePath, "i18n", "messages"))
}

func generatedModuleImportPath(paths projectlayout.ProjectLayout, moduleName string) string {
	relativePath := strings.TrimSpace(paths.GeneratedImport)
	if relativePath == "" {
		relativePath = "web/generated"
	}
	return appImportPath(paths.AppModulePath, path.Join(relativePath, moduleName))
}

func viewImportPath(paths projectlayout.ProjectLayout) string {
	relativePath := strings.TrimSpace(paths.ViewImport)
	if relativePath == "" {
		relativePath = "web/view"
	}
	return appImportPath(paths.AppModulePath, relativePath)
}

func routesImportPath(paths projectlayout.ProjectLayout) string {
	relativePath := strings.TrimSpace(paths.RoutesImport)
	if relativePath == "" {
		relativePath = "web/routes"
	}
	return appImportPath(paths.AppModulePath, relativePath)
}

func routesImportPathForRouteID(paths projectlayout.ProjectLayout, routeID string) string {
	base := strings.TrimSpace(paths.RoutesImport)
	if base == "" {
		base = "web/routes"
	}
	trimmedRouteID := strings.Trim(strings.TrimSpace(routeID), "/")
	if trimmedRouteID == "" {
		return appImportPath(paths.AppModulePath, base)
	}
	return appImportPath(paths.AppModulePath, path.Join(base, trimmedRouteID))
}

func sourceModuleName(segments []routeSegment) string {
	parts := make([]string, 0, len(segments)+2)
	parts = append(parts, "r", "source")
	if len(segments) == 0 {
		parts = append(parts, "root")
	} else {
		for _, segment := range segments {
			parts = append(parts, segment.SafePart())
		}
	}
	return strings.Join(parts, "_")
}
