// Code generated by framework/cmd/i18nkeygen. DO NOT EDIT.
package i18n

type Key string

const (
	KeyChannelAll                    Key = "channel.all"
	KeyChannelAny                    Key = "channel.any"
	KeyChannelMicroTales             Key = "channel.microTales"
	KeyChannelSectionAuthors         Key = "channel.section.authors"
	KeyChannelSectionChannels        Key = "channel.section.channels"
	KeyChannelSectionNoteType        Key = "channel.section.noteType"
	KeyChannelSectionTags            Key = "channel.section.tags"
	KeyChannelTales                  Key = "channel.tales"
	KeyChannelsPageBack              Key = "channels.page.back"
	KeyChannelsPageHint              Key = "channels.page.hint"
	KeyChannelsPageTitle             Key = "channels.page.title"
	KeyComposerReadOnly              Key = "composer.readOnly"
	KeyContextFeed                   Key = "context.feed"
	KeyContextLongDescription        Key = "context.longDescription"
	KeyContextShortDescription       Key = "context.shortDescription"
	KeyContextTagDescription         Key = "context.tagDescription"
	KeyContextTagSubtitle            Key = "context.tagSubtitle"
	KeyContextTypeSubtitle           Key = "context.typeSubtitle"
	KeyEmptyAuthor                   Key = "empty.author"
	KeyEmptyMicro                    Key = "empty.micro"
	KeyEmptyRoot                     Key = "empty.root"
	KeyEmptyTag                      Key = "empty.tag"
	KeyEmptyTales                    Key = "empty.tales"
	KeyLayoutAriaBlogHome            Key = "layout.aria.blogHome"
	KeyLayoutAriaChannelHeader       Key = "layout.aria.channelHeader"
	KeyLayoutAriaChannelList         Key = "layout.aria.channelList"
	KeyLayoutAriaNotesChannel        Key = "layout.aria.notesChannel"
	KeyLayoutAriaUtility             Key = "layout.aria.utility"
	KeyLayoutAriaWorkspaceNavigation Key = "layout.aria.workspaceNavigation"
	KeyLayoutChannelsButton          Key = "layout.channelsButton"
	KeyLayoutFooterAnalyticsLink     Key = "layout.footer.analyticsLink"
	KeyLayoutFooterAnalyticsPrefix   Key = "layout.footer.analyticsPrefix"
	KeyLayoutFooterOpensourceLink    Key = "layout.footer.opensourceLink"
	KeyLayoutFooterOpensourcePrefix  Key = "layout.footer.opensourcePrefix"
	KeyLayoutFooterStackPrefix       Key = "layout.footer.stackPrefix"
	KeyLayoutGuildBlog               Key = "layout.guild.blog"
	KeyLayoutGuildOnline             Key = "layout.guild.online"
	KeyLayoutGuildServer             Key = "layout.guild.server"
	KeyLayoutSearchClear             Key = "layout.search.clear"
	KeyLayoutSearchPlaceholder       Key = "layout.search.placeholder"
	KeyLayoutSearchSubmit            Key = "layout.search.submit"
	KeyLayoutTitleAll                Key = "layout.title.all"
	KeyLayoutTitleMicroTales         Key = "layout.title.microTales"
	KeyLayoutTitleNotes              Key = "layout.title.notes"
	KeyLayoutTitleTales              Key = "layout.title.tales"
	KeyMarkdownCodeCopied            Key = "markdown.code.copied"
	KeyMarkdownCodeCopy              Key = "markdown.code.copy"
	KeyMarkdownCodePlainText         Key = "markdown.code.plainText"
	KeyMarkdownPlaceholderCodeBlock  Key = "markdown.placeholder.codeBlock"
	KeyMarkdownPlaceholderImage      Key = "markdown.placeholder.image"
	KeyMarkdownPlaceholderTable      Key = "markdown.placeholder.table"
	KeyNoteAttachmentLabelPrefix     Key = "note.attachmentLabelPrefix"
	KeyNoteBack                      Key = "note.back"
	KeyNoteFeaturedAttachment        Key = "note.featuredAttachment"
	KeyNoteOpenFull                  Key = "note.openFull"
	KeyNotePublishedPrefix           Key = "note.publishedPrefix"
	KeyNoteTitleFallback             Key = "note.title.fallback"
	KeyNoteUnknownAuthor             Key = "note.unknownAuthor"
	KeyNotesAriaFeed                 Key = "notes.aria.feed"
	KeyNotfoundBack                  Key = "notfound.back"
	KeyNotfoundKicker                Key = "notfound.kicker"
	KeyNotfoundOpenChannels          Key = "notfound.openChannels"
	KeyNotfoundPageTitle             Key = "notfound.pageTitle"
	KeyNotfoundSummaryPrefix         Key = "notfound.summaryPrefix"
	KeyNotfoundSummarySuffix         Key = "notfound.summarySuffix"
	KeyNotfoundTitle                 Key = "notfound.title"
	KeyPagerFirst                    Key = "pager.first"
	KeyPagerLast                     Key = "pager.last"
	KeyPagerNext                     Key = "pager.next"
	KeyPagerPage                     Key = "pager.page"
	KeyPagerPrev                     Key = "pager.prev"
	KeySeoAuthorDescription          Key = "seo.author.description"
	KeySeoChannelsDescription        Key = "seo.channels.description"
	KeySeoMicroTalesDescription      Key = "seo.microTales.description"
	KeySeoNoteDescription            Key = "seo.note.description"
	KeySeoNotesJSONLDDescription     Key = "seo.notesJSONLD.description"
	KeySeoNotesJSONLDName            Key = "seo.notesJSONLD.name"
	KeySeoPublisherName              Key = "seo.publisher.name"
	KeySeoRootDescription            Key = "seo.root.description"
	KeySeoRootTitle                  Key = "seo.root.title"
	KeySeoSiteDescription            Key = "seo.site.description"
	KeySeoSiteName                   Key = "seo.site.name"
	KeySeoTagDescription             Key = "seo.tag.description"
	KeySeoTalesDescription           Key = "seo.tales.description"
)

var AllKeys = []Key{
	KeyChannelAll,
	KeyChannelAny,
	KeyChannelMicroTales,
	KeyChannelSectionAuthors,
	KeyChannelSectionChannels,
	KeyChannelSectionNoteType,
	KeyChannelSectionTags,
	KeyChannelTales,
	KeyChannelsPageBack,
	KeyChannelsPageHint,
	KeyChannelsPageTitle,
	KeyComposerReadOnly,
	KeyContextFeed,
	KeyContextLongDescription,
	KeyContextShortDescription,
	KeyContextTagDescription,
	KeyContextTagSubtitle,
	KeyContextTypeSubtitle,
	KeyEmptyAuthor,
	KeyEmptyMicro,
	KeyEmptyRoot,
	KeyEmptyTag,
	KeyEmptyTales,
	KeyLayoutAriaBlogHome,
	KeyLayoutAriaChannelHeader,
	KeyLayoutAriaChannelList,
	KeyLayoutAriaNotesChannel,
	KeyLayoutAriaUtility,
	KeyLayoutAriaWorkspaceNavigation,
	KeyLayoutChannelsButton,
	KeyLayoutFooterAnalyticsLink,
	KeyLayoutFooterAnalyticsPrefix,
	KeyLayoutFooterOpensourceLink,
	KeyLayoutFooterOpensourcePrefix,
	KeyLayoutFooterStackPrefix,
	KeyLayoutGuildBlog,
	KeyLayoutGuildOnline,
	KeyLayoutGuildServer,
	KeyLayoutSearchClear,
	KeyLayoutSearchPlaceholder,
	KeyLayoutSearchSubmit,
	KeyLayoutTitleAll,
	KeyLayoutTitleMicroTales,
	KeyLayoutTitleNotes,
	KeyLayoutTitleTales,
	KeyMarkdownCodeCopied,
	KeyMarkdownCodeCopy,
	KeyMarkdownCodePlainText,
	KeyMarkdownPlaceholderCodeBlock,
	KeyMarkdownPlaceholderImage,
	KeyMarkdownPlaceholderTable,
	KeyNoteAttachmentLabelPrefix,
	KeyNoteBack,
	KeyNoteFeaturedAttachment,
	KeyNoteOpenFull,
	KeyNotePublishedPrefix,
	KeyNoteTitleFallback,
	KeyNoteUnknownAuthor,
	KeyNotesAriaFeed,
	KeyNotfoundBack,
	KeyNotfoundKicker,
	KeyNotfoundOpenChannels,
	KeyNotfoundPageTitle,
	KeyNotfoundSummaryPrefix,
	KeyNotfoundSummarySuffix,
	KeyNotfoundTitle,
	KeyPagerFirst,
	KeyPagerLast,
	KeyPagerNext,
	KeyPagerPage,
	KeyPagerPrev,
	KeySeoAuthorDescription,
	KeySeoChannelsDescription,
	KeySeoMicroTalesDescription,
	KeySeoNoteDescription,
	KeySeoNotesJSONLDDescription,
	KeySeoNotesJSONLDName,
	KeySeoPublisherName,
	KeySeoRootDescription,
	KeySeoRootTitle,
	KeySeoSiteDescription,
	KeySeoSiteName,
	KeySeoTagDescription,
	KeySeoTalesDescription,
}

var DefaultMessages = map[Key]string{
	KeyChannelAll:                    "All",
	KeyChannelAny:                    "All",
	KeyChannelMicroTales:             "Micro-tales",
	KeyChannelSectionAuthors:         "authors",
	KeyChannelSectionChannels:        "channels",
	KeyChannelSectionNoteType:        "note type",
	KeyChannelSectionTags:            "tags",
	KeyChannelTales:                  "Tales",
	KeyChannelsPageBack:              "Back to feed",
	KeyChannelsPageHint:              "Use the left channel list to navigate.",
	KeyChannelsPageTitle:             "Channels",
	KeyComposerReadOnly:              "You do not have permission to send messages in this channel. It is READ-only! :)",
	KeyContextFeed:                   "feed",
	KeyContextLongDescription:        "long-form notes",
	KeyContextShortDescription:       "short notes",
	KeyContextTagDescription:         "notes filtered by tag",
	KeyContextTagSubtitle:            "tag",
	KeyContextTypeSubtitle:           "type",
	KeyEmptyAuthor:                   "this author has no published notes yet.",
	KeyEmptyMicro:                    "no micro-tales found for this filter.",
	KeyEmptyRoot:                     "no notes found for this filter.",
	KeyEmptyTag:                      "no notes found for this tag.",
	KeyEmptyTales:                    "no tales found for this filter.",
	KeyLayoutAriaBlogHome:            "blog home",
	KeyLayoutAriaChannelHeader:       "channel header",
	KeyLayoutAriaChannelList:         "channel list",
	KeyLayoutAriaNotesChannel:        "notes channel",
	KeyLayoutAriaUtility:             "utility",
	KeyLayoutAriaWorkspaceNavigation: "workspace navigation",
	KeyLayoutChannelsButton:          "Channels",
	KeyLayoutFooterAnalyticsLink:     "Lovely Eye repo",
	KeyLayoutFooterAnalyticsPrefix:   "analytics by:",
	KeyLayoutFooterOpensourceLink:    "Browse the source on GitHub",
	KeyLayoutFooterOpensourcePrefix:  "the code of this project is developed publicly:",
	KeyLayoutFooterStackPrefix:       "stack:",
	KeyLayoutGuildBlog:               "Blog",
	KeyLayoutGuildOnline:             "online",
	KeyLayoutGuildServer:             "Server",
	KeyLayoutSearchClear:             "Clear",
	KeyLayoutSearchPlaceholder:       "Search notes",
	KeyLayoutSearchSubmit:            "Search",
	KeyLayoutTitleAll:                "All",
	KeyLayoutTitleMicroTales:         "Micro-tales",
	KeyLayoutTitleNotes:              "Notes",
	KeyLayoutTitleTales:              "Tales",
	KeyMarkdownCodeCopied:            "copied",
	KeyMarkdownCodeCopy:              "copy",
	KeyMarkdownCodePlainText:         "plain text",
	KeyMarkdownPlaceholderCodeBlock:  "[code block]",
	KeyMarkdownPlaceholderImage:      "[image]",
	KeyMarkdownPlaceholderTable:      "[table]",
	KeyNoteAttachmentLabelPrefix:     "attachment",
	KeyNoteBack:                      "Back to notes",
	KeyNoteFeaturedAttachment:        "featured attachment",
	KeyNoteOpenFull:                  "Open full note",
	KeyNotePublishedPrefix:           "published",
	KeyNoteTitleFallback:             "Note",
	KeyNoteUnknownAuthor:             "unknown author",
	KeyNotesAriaFeed:                 "notes feed",
	KeyNotfoundBack:                  "Back to notes",
	KeyNotfoundKicker:                "error / 404",
	KeyNotfoundOpenChannels:          "Open channels",
	KeyNotfoundPageTitle:             "404 Not Found",
	KeyNotfoundSummaryPrefix:         "The channel",
	KeyNotfoundSummarySuffix:         "was not found on this server.",
	KeyNotfoundTitle:                 "Signal lost",
	KeyPagerFirst:                    "first",
	KeyPagerLast:                     "last",
	KeyPagerNext:                     "next",
	KeyPagerPage:                     "page",
	KeyPagerPrev:                     "prev",
	KeySeoAuthorDescription:          "Browse notes by this author.",
	KeySeoChannelsDescription:        "Browse available channels and filters for the blog feed.",
	KeySeoMicroTalesDescription:      "Read short-form micro-tales from the blog feed.",
	KeySeoNoteDescription:            "Read this note from the blog archive.",
	KeySeoNotesJSONLDDescription:     "Explore a collection of notes on various topics, including coding, web performance, SEO, AI workflows, and book takeaways. Each note is designed to provide quick insights and actionable tips for developers and tech enthusiasts.",
	KeySeoNotesJSONLDName:            "Notes",
	KeySeoPublisherName:              "RevoTale",
	KeySeoRootDescription:            "Dive into concise notes packed with actionable tips on coding, web-performance, SEO, AI workflows, book takeaways and more—updated regularly on RevoTale. ",
	KeySeoRootTitle:                  "Notes - Quick Coding, Experience, Open Source, SEO & Science Insights",
	KeySeoSiteDescription:            "A multilingual note feed with tales and micro-tales.",
	KeySeoSiteName:                   "RevoTale",
	KeySeoTagDescription:             "Browse notes for this tag.",
	KeySeoTalesDescription:           "Read long-form tales from the blog feed.",
}
