package templcssgen

import (
	"bytes"
	"fmt"
	"go/ast"
	gofmt "go/format"
	goparser "go/parser"
	"go/token"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	bundlertemplgen "github.com/RevoTale/no-js/internal/bundler/templgen"
	"github.com/RevoTale/no-js/internal/bundler/viewcontract"
	"github.com/RevoTale/no-js/internal/projectlayout"
	templparser "github.com/a-h/templ/parser/v2"
)

const (
	generatedHeader            = "// Code generated by cmd/templcssgen. DO NOT EDIT."
	packageExportFileName      = "templ_css_exports_gen.go"
	packageExportFuncName      = "NoJSTemplCSSClasses"
	registryFileName           = "templ_css_gen.go"
	generatedWorkspaceDirName  = "templcss"
	defaultStylesheetAssetPath = "styles/templ.css"
	frameworkModuleTemplImport = "github.com/a-h/templ"
)

type Config struct {
	Layout projectlayout.ProjectLayout
}

type packageKind string

const (
	routePackageKind     packageKind = "routes"
	componentPackageKind packageKind = "components"
)

type cssScanRoot struct {
	Dir             string
	GeneratedPrefix string
	Kind            packageKind
}

type packageSpec struct {
	Kind         packageKind
	SourceDir    string
	GeneratedDir string
	ImportPath   string
	Package      string
	Functions    []string
}

func Run(cfg Config) error {
	layout, err := validateLayout(cfg.Layout)
	if err != nil {
		return err
	}
	viewHooks, err := viewcontract.Inspect(layout.ViewDir)
	if err != nil {
		return fmt.Errorf("inspect view contract: %w", err)
	}

	scanRoots := cssScanRoots(layout)
	if err := cleanupPackageExports(scanRoots); err != nil {
		return err
	}

	packages, err := collectPackages(layout, scanRoots)
	if err != nil {
		return err
	}

	if err := prepareGeneratedWorkspace(layout, packages); err != nil {
		return err
	}

	if err := writeRegistry(layout, packages, viewHooks.HasTemplCSSVariantsHook); err != nil {
		return err
	}

	return nil
}

func validateLayout(layout projectlayout.ProjectLayout) (projectlayout.ProjectLayout, error) {
	if strings.TrimSpace(layout.RootDir) == "" {
		return projectlayout.ProjectLayout{}, fmt.Errorf("project root dir is required")
	}
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return projectlayout.ProjectLayout{}, fmt.Errorf("routes dir is required")
	}
	if strings.TrimSpace(layout.GeneratedDir) == "" {
		return projectlayout.ProjectLayout{}, fmt.Errorf("generated dir is required")
	}
	if strings.TrimSpace(layout.ViewImport) == "" {
		return projectlayout.ProjectLayout{}, fmt.Errorf("view import path is required")
	}
	if strings.TrimSpace(layout.AppModulePath) == "" {
		return projectlayout.ProjectLayout{}, fmt.Errorf("app module path is required")
	}

	return layout, nil
}

func cssScanRoots(layout projectlayout.ProjectLayout) []cssScanRoot {
	roots := []cssScanRoot{{
		Dir:             layout.RoutesDir,
		GeneratedPrefix: string(routePackageKind),
		Kind:            routePackageKind,
	}}
	componentsDir := filepath.Join(filepath.Dir(layout.RoutesDir), "components")
	if info, err := os.Stat(componentsDir); err == nil && info.IsDir() {
		roots = append(roots, cssScanRoot{
			Dir:             filepath.ToSlash(componentsDir),
			GeneratedPrefix: string(componentPackageKind),
			Kind:            componentPackageKind,
		})
	}

	sort.Slice(roots, func(i int, j int) bool {
		return roots[i].Dir < roots[j].Dir
	})
	return roots
}

func cleanupPackageExports(roots []cssScanRoot) error {
	for _, root := range roots {
		if strings.TrimSpace(root.Dir) == "" {
			continue
		}
		info, err := os.Stat(root.Dir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("stat css scan root %q: %w", root.Dir, err)
		}
		if !info.IsDir() {
			continue
		}

		if err := filepath.WalkDir(root.Dir, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || filepath.Base(filePath) != packageExportFileName {
				return nil
			}
			if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("remove stale css export %q: %w", filePath, err)
			}
			return nil
		}); err != nil {
			return err
		}
	}

	return nil
}

func collectPackages(layout projectlayout.ProjectLayout, roots []cssScanRoot) ([]packageSpec, error) {
	byDir := make(map[string]*packageSpec)

	for _, root := range roots {
		files, err := collectTemplFiles(root.Dir)
		if err != nil {
			return nil, err
		}

		for _, fileName := range files {
			parsed, err := templparser.Parse(fileName)
			if err != nil {
				return nil, fmt.Errorf("parse %q: %w", fileName, err)
			}

			dir := filepath.ToSlash(filepath.Dir(fileName))
			pkg, err := ensurePackage(layout, byDir, root, dir, parsed.Package.Expression.Value)
			if err != nil {
				return nil, err
			}

			for _, node := range parsed.Nodes {
				css, ok := node.(*templparser.CSSTemplate)
				if !ok {
					continue
				}

				funcName, include, err := parseZeroArgCSSFunc(css.Expression.Value)
				if err != nil {
					return nil, fmt.Errorf("parse css declaration in %q: %w", fileName, err)
				}
				if !include {
					continue
				}

				pkg.Functions = append(pkg.Functions, funcName)
			}
		}
	}

	packages := make([]packageSpec, 0, len(byDir))
	for _, pkg := range byDir {
		pkg.Functions = compactSortedStrings(pkg.Functions)
		if len(pkg.Functions) == 0 {
			continue
		}
		packages = append(packages, *pkg)
	}

	sort.Slice(packages, func(i int, j int) bool {
		return packages[i].ImportPath < packages[j].ImportPath
	})

	return packages, nil
}

func collectTemplFiles(root string) ([]string, error) {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat scan root %q: %w", root, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("scan root %q is not a directory", root)
	}

	files := make([]string, 0, 8)
	if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(filePath) != ".templ" {
			return nil
		}
		files = append(files, filepath.ToSlash(filePath))
		return nil
	}); err != nil {
		return nil, fmt.Errorf("walk scan root %q: %w", root, err)
	}

	sort.Strings(files)
	return files, nil
}

func ensurePackage(
	layout projectlayout.ProjectLayout,
	byDir map[string]*packageSpec,
	root cssScanRoot,
	dir string,
	packageExpr string,
) (*packageSpec, error) {
	if existing, ok := byDir[dir]; ok {
		return existing, nil
	}

	packageName, err := parsePackageName(packageExpr)
	if err != nil {
		return nil, fmt.Errorf("parse package declaration for %q: %w", dir, err)
	}

	relativeDir, err := filepath.Rel(root.Dir, dir)
	if err != nil {
		return nil, fmt.Errorf("resolve relative package dir for %q: %w", dir, err)
	}
	relativeDir = filepath.ToSlash(relativeDir)
	if strings.HasPrefix(relativeDir, "../") {
		return nil, fmt.Errorf("package dir %q must stay inside %q", dir, root.Dir)
	}

	generatedDir := filepath.Join(layout.GeneratedDir, generatedWorkspaceDirName, root.GeneratedPrefix)
	importPath := path.Join(layout.AppModulePath, layout.GeneratedImport, generatedWorkspaceDirName, root.GeneratedPrefix)
	if relativeDir != "." && strings.TrimSpace(relativeDir) != "" {
		generatedDir = filepath.Join(generatedDir, filepath.FromSlash(relativeDir))
		importPath = path.Join(importPath, relativeDir)
	}

	pkg := &packageSpec{
		Kind:         root.Kind,
		SourceDir:    dir,
		GeneratedDir: filepath.ToSlash(generatedDir),
		ImportPath:   importPath,
		Package:      packageName,
	}
	byDir[dir] = pkg
	return pkg, nil
}

func parsePackageName(packageExpr string) (string, error) {
	file, err := goparser.ParseFile(token.NewFileSet(), "templ_css_package.go", packageExpr+"\n", 0)
	if err != nil {
		return "", err
	}
	if file.Name == nil || strings.TrimSpace(file.Name.Name) == "" {
		return "", fmt.Errorf("package name is required")
	}
	return file.Name.Name, nil
}

func parseZeroArgCSSFunc(expression string) (string, bool, error) {
	file, err := goparser.ParseFile(
		token.NewFileSet(),
		"templ_css_signature.go",
		"package p\nfunc "+expression+" {}\n",
		0,
	)
	if err != nil {
		return "", false, err
	}
	if len(file.Decls) != 1 {
		return "", false, fmt.Errorf("expected a single declaration")
	}

	funcDecl, ok := file.Decls[0].(*ast.FuncDecl)
	if !ok {
		return "", false, fmt.Errorf("expected a function declaration")
	}
	if funcDecl.Recv != nil {
		return "", false, nil
	}
	if funcDecl.Type.Params != nil && len(funcDecl.Type.Params.List) > 0 {
		return "", false, nil
	}
	if funcDecl.Name == nil || strings.TrimSpace(funcDecl.Name.Name) == "" {
		return "", false, fmt.Errorf("function name is required")
	}

	return funcDecl.Name.Name, true, nil
}

func prepareGeneratedWorkspace(layout projectlayout.ProjectLayout, packages []packageSpec) error {
	workspaceDir := filepath.Join(layout.GeneratedDir, generatedWorkspaceDirName)
	if err := os.RemoveAll(workspaceDir); err != nil {
		return fmt.Errorf("clean templ css workspace %q: %w", filepath.ToSlash(workspaceDir), err)
	}
	if len(packages) == 0 {
		return nil
	}

	for _, pkg := range packages {
		if err := mirrorPackageSource(pkg); err != nil {
			return err
		}
		if err := writePackageExport(pkg); err != nil {
			return err
		}
	}

	if err := bundlertemplgen.Run(bundlertemplgen.Config{
		Paths:    []string{workspaceDir},
		BasePath: layout.RootDir,
	}); err != nil {
		return fmt.Errorf("generate templ css workspace templates: %w", err)
	}

	return nil
}

func mirrorPackageSource(pkg packageSpec) error {
	entries, err := os.ReadDir(pkg.SourceDir)
	if err != nil {
		return fmt.Errorf("read css package dir %q: %w", pkg.SourceDir, err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		fileName := entry.Name()
		if !shouldCopyPackageFile(pkg.Kind, fileName) {
			continue
		}

		sourcePath := filepath.Join(pkg.SourceDir, fileName)
		targetPath := filepath.Join(pkg.GeneratedDir, fileName)
		if err := copyFile(sourcePath, targetPath); err != nil {
			return err
		}
	}

	return nil
}

func shouldCopyPackageFile(kind packageKind, fileName string) bool {
	switch {
	case strings.HasSuffix(fileName, ".templ"):
		return true
	case filepath.Ext(fileName) != ".go":
		return false
	case strings.HasSuffix(fileName, "_test.go"):
		return false
	case strings.HasSuffix(fileName, "_templ.go"):
		return false
	case fileName == packageExportFileName:
		return false
	}

	if kind == routePackageKind {
		switch fileName {
		case "route.go", "robots.go", "feed.go", "sitemap.go":
			return false
		}
	}

	return true
}

func copyFile(sourcePath string, targetPath string) error {
	content, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("read %q: %w", filepath.ToSlash(sourcePath), err)
	}
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return fmt.Errorf("create dir for %q: %w", filepath.ToSlash(targetPath), err)
	}
	if err := os.WriteFile(targetPath, content, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", filepath.ToSlash(targetPath), err)
	}
	return nil
}

func writePackageExport(pkg packageSpec) error {
	buffer := &bytes.Buffer{}
	buffer.WriteString(generatedHeader + "\n")
	buffer.WriteString("package " + pkg.Package + "\n\n")
	buffer.WriteString("import (\n")
	buffer.WriteString("\t" + quote(frameworkModuleTemplImport) + "\n")
	buffer.WriteString(")\n\n")
	buffer.WriteString("func " + packageExportFuncName + "() []templ.CSSClass {\n")
	buffer.WriteString("\treturn []templ.CSSClass{\n")
	for _, funcName := range pkg.Functions {
		buffer.WriteString("\t\t" + funcName + "(),\n")
	}
	buffer.WriteString("\t}\n")
	buffer.WriteString("}\n")

	return writeFormattedFile(filepath.Join(pkg.GeneratedDir, packageExportFileName), buffer.Bytes())
}

func writeRegistry(layout projectlayout.ProjectLayout, packages []packageSpec, hasVariantsHook bool) error {
	buffer := &bytes.Buffer{}
	buffer.WriteString(generatedHeader + "\n")
	buffer.WriteString("package gen\n\n")
	buffer.WriteString("import (\n")
	buffer.WriteString("\t" + quote(frameworkModuleTemplImport) + "\n")
	if hasVariantsHook {
		buffer.WriteString("\t" + quote(path.Join(layout.AppModulePath, layout.ViewImport)) + "\n")
	}
	for idx, pkg := range packages {
		buffer.WriteString("\tcsspkg" + fmt.Sprint(idx) + " " + quote(pkg.ImportPath) + "\n")
	}
	buffer.WriteString(")\n\n")
	buffer.WriteString("func TemplCSSClasses() []templ.CSSClass {\n")
	buffer.WriteString("\tclasses := make([]templ.CSSClass, 0")
	for _, pkg := range packages {
		buffer.WriteString(" + " + fmt.Sprint(len(pkg.Functions)))
	}
	buffer.WriteString(")\n")
	for idx := range packages {
		buffer.WriteString("\tclasses = append(classes, csspkg" + fmt.Sprint(idx) + "." + packageExportFuncName + "()...)\n")
	}
	if hasVariantsHook {
		buffer.WriteString("\tclasses = append(classes, view.TemplCSSVariants()...)\n")
	}
	buffer.WriteString("\treturn classes\n")
	buffer.WriteString("}\n")

	return writeFormattedFile(filepath.Join(layout.GeneratedDir, registryFileName), buffer.Bytes())
}

func writeFormattedFile(filePath string, source []byte) error {
	formatted, err := gofmt.Source(source)
	if err != nil {
		return fmt.Errorf("format %q: %w", filepath.ToSlash(filePath), err)
	}
	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		return fmt.Errorf("create dir for %q: %w", filepath.ToSlash(filePath), err)
	}
	if err := os.WriteFile(filePath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", filepath.ToSlash(filePath), err)
	}
	return nil
}

func compactSortedStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}

	sort.Strings(values)
	out := values[:0]
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if len(out) > 0 && out[len(out)-1] == trimmed {
			continue
		}
		out = append(out, trimmed)
	}
	return out
}

func quote(value string) string {
	return fmt.Sprintf("%q", value)
}
