package clientassets

import (
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/RevoTale/no-js/framework/metagen"
	frameworkrouter "github.com/RevoTale/no-js/framework/router"
	"github.com/RevoTale/no-js/internal/filesystem"
	"github.com/RevoTale/no-js/internal/projectlayout"
	"github.com/evanw/esbuild/pkg/api"
	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/css"
)

const generatedHeader = "// Code generated by cmd/no-js client assets. DO NOT EDIT."

var (
	packageRE      = regexp.MustCompile(`(?m)^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)`)
	quotedImportRE = regexp.MustCompile(`"([^"]+)"`)
)

type Config struct {
	Layout projectlayout.ProjectLayout
	Routes []RouteSpec
}

type PrepareStaticSourceConfig struct {
	Layout    projectlayout.ProjectLayout
	SourceDir string
}

type RouteSpec struct {
	RouteID       string
	TemplatePaths []string
}

type Plan struct {
	RouteAssets    map[string]metagen.ClientAssets
	NotFoundAssets map[string]metagen.ClientAssets

	cssFiles    []*cssAsset
	scriptFiles []*scriptAsset
	routes      []*routeBundle
}

type cssAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	Transformed string
	Classes     []cssClass
}

type cssClass struct {
	Original  string
	Constant  string
	Generated string
}

type scriptAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	AssetPath   string
	FuncName    string
	VarName     string
}

type routeBundle struct {
	RouteID     string
	AssetSlug   string
	CSSPath     string
	JSPath      string
	CSSFiles    []*cssAsset
	ScriptFiles []*scriptAsset
}

type assetIndex struct {
	cssByDir    map[string][]*cssAsset
	scriptByDir map[string][]*scriptAsset
	cssFiles    []*cssAsset
	scriptFiles []*scriptAsset
}

type generatedClassAllocator struct {
	used map[string]string
}

type cssClassMapper struct {
	layout     projectlayout.ProjectLayout
	filePath   string
	allocator  *generatedClassAllocator
	filePrefix string
	seen       map[string]cssClass
	constants  map[string]int
}

type cssTokenStreamRewriter struct {
	mapper          *cssClassMapper
	pendingClassDot bool
}

func Generate(cfg Config) (Plan, error) {
	plan, err := BuildPlan(cfg)
	if err != nil {
		return Plan{}, err
	}
	if err := cleanGeneratedHelpers(cfg.Layout); err != nil {
		return Plan{}, err
	}
	for _, css := range plan.cssFiles {
		if err := writeCSSHelper(css); err != nil {
			return Plan{}, err
		}
	}
	for _, script := range plan.scriptFiles {
		if err := writeScriptHelper(script); err != nil {
			return Plan{}, err
		}
	}
	return plan.public(), nil
}

func BuildPlan(cfg Config) (Plan, error) {
	layout := cfg.Layout
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return Plan{}, fmt.Errorf("routes dir is required")
	}

	routes := cfg.Routes
	if len(routes) == 0 {
		discovered, err := DiscoverRouteSpecs(layout)
		if err != nil {
			return Plan{}, err
		}
		routes = discovered
	}

	index, err := discoverAssets(layout)
	if err != nil {
		return Plan{}, err
	}

	notFounds, err := DiscoverNotFoundSpecs(layout)
	if err != nil {
		return Plan{}, err
	}

	bundles := make([]*routeBundle, 0, len(routes)+len(notFounds))
	routeAssets := make(map[string]metagen.ClientAssets, len(routes))
	for _, route := range routes {
		bundle := buildRouteBundle(layout, index, route)
		bundle.AssetSlug = assetSlug(route.RouteID)
		routeAssets[route.RouteID] = bundleClientAssets(bundle)
		bundles = append(bundles, bundle)
	}

	notFoundAssets := make(map[string]metagen.ClientAssets, len(notFounds))
	for _, notFound := range notFounds {
		bundle := buildRouteBundle(layout, index, notFound)
		bundle.AssetSlug = notFoundAssetSlug(notFound.RouteID)
		notFoundAssets[notFound.RouteID] = bundleClientAssets(bundle)
		bundles = append(bundles, bundle)
	}

	return Plan{
		RouteAssets:    routeAssets,
		NotFoundAssets: notFoundAssets,
		cssFiles:       index.cssFiles,
		scriptFiles:    index.scriptFiles,
		routes:         bundles,
	}, nil
}

func HasClientAssets(layout projectlayout.ProjectLayout) (bool, error) {
	roots := clientAssetRoots(layout)
	for _, root := range roots {
		if strings.TrimSpace(root) == "" {
			continue
		}
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return false, err
		}
		found := false
		err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				if shouldSkipDir(filePath, layout) && filePath != root {
					return fs.SkipDir
				}
				return nil
			}
			if isCSSFile(filePath) || isScriptFile(filePath) {
				found = true
				return fs.SkipAll
			}
			return nil
		})
		if err != nil && !isSkipAll(err) {
			return false, err
		}
		if found {
			return true, nil
		}
	}
	return false, nil
}

func PrepareStaticSource(cfg PrepareStaticSourceConfig) (string, func() error, error) {
	layout := cfg.Layout
	stageDir, err := os.MkdirTemp("", "no-js-client-assets-*")
	if err != nil {
		return "", nil, fmt.Errorf("create client assets stage: %w", err)
	}
	cleanup := func() error { return os.RemoveAll(stageDir) }

	if strings.TrimSpace(cfg.SourceDir) != "" {
		if info, statErr := os.Stat(cfg.SourceDir); statErr == nil && info.IsDir() {
			if err := filesystem.CopyTree(cfg.SourceDir, stageDir); err != nil {
				_ = cleanup()
				return "", nil, fmt.Errorf("copy static source: %w", err)
			}
		} else if statErr != nil && !os.IsNotExist(statErr) {
			_ = cleanup()
			return "", nil, fmt.Errorf("stat static source: %w", statErr)
		}
	}

	plan, err := BuildPlan(Config{Layout: layout})
	if err != nil {
		_ = cleanup()
		return "", nil, err
	}
	if err := writeStaticOutputs(stageDir, plan); err != nil {
		_ = cleanup()
		return "", nil, err
	}
	return stageDir, cleanup, nil
}

func (plan Plan) public() Plan {
	out := Plan{
		RouteAssets:    map[string]metagen.ClientAssets{},
		NotFoundAssets: map[string]metagen.ClientAssets{},
	}
	for routeID, assets := range plan.RouteAssets {
		out.RouteAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	for routeID, assets := range plan.NotFoundAssets {
		out.NotFoundAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	return out
}

func discoverAssets(layout projectlayout.ProjectLayout) (*assetIndex, error) {
	index := &assetIndex{
		cssByDir:    map[string][]*cssAsset{},
		scriptByDir: map[string][]*scriptAsset{},
	}
	classAllocator := newGeneratedClassAllocator()
	for _, root := range clientAssetRoots(layout) {
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("stat client asset root %q: %w", root, err)
		}
		if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				if shouldSkipDir(filePath, layout) && filePath != root {
					return fs.SkipDir
				}
				return nil
			}
			if isGeneratedHelper(filePath) {
				return nil
			}
			switch {
			case isCSSFile(filePath):
				asset, err := newCSSAsset(layout, filePath, classAllocator)
				if err != nil {
					return err
				}
				index.cssByDir[asset.PackageDir] = append(index.cssByDir[asset.PackageDir], asset)
				index.cssFiles = append(index.cssFiles, asset)
			case isScriptFile(filePath):
				asset, err := newScriptAsset(layout, filePath)
				if err != nil {
					return err
				}
				index.scriptByDir[asset.PackageDir] = append(index.scriptByDir[asset.PackageDir], asset)
				index.scriptFiles = append(index.scriptFiles, asset)
			}
			return nil
		}); err != nil {
			return nil, err
		}
	}

	sort.Slice(index.cssFiles, func(i int, j int) bool {
		return index.cssFiles[i].SourcePath < index.cssFiles[j].SourcePath
	})
	sort.Slice(index.scriptFiles, func(i int, j int) bool {
		return index.scriptFiles[i].SourcePath < index.scriptFiles[j].SourcePath
	})
	return index, nil
}

func newCSSAsset(
	layout projectlayout.ProjectLayout,
	filePath string,
	classAllocator *generatedClassAllocator,
) (*cssAsset, error) {
	packageName, err := packageNameForDir(filepath.Dir(filePath))
	if err != nil {
		return nil, err
	}
	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read css %q: %w", filePath, err)
	}
	classes, transformed, err := transformCSSModule(layout, filePath, string(content), classAllocator)
	if err != nil {
		return nil, err
	}
	return &cssAsset{
		SourcePath:  filePath,
		PackageDir:  filepath.Dir(filePath),
		PackageName: packageName,
		HelperPath:  strings.TrimSuffix(filePath, ".css") + ".css_gen.go",
		Transformed: transformed,
		Classes:     classes,
	}, nil
}

func newScriptAsset(layout projectlayout.ProjectLayout, filePath string) (*scriptAsset, error) {
	packageName, err := packageNameForDir(filepath.Dir(filePath))
	if err != nil {
		return nil, err
	}
	baseName := strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
	assetPath, err := logicalScriptAssetPath(layout, filePath)
	if err != nil {
		return nil, err
	}
	return &scriptAsset{
		SourcePath:  filePath,
		PackageDir:  filepath.Dir(filePath),
		PackageName: packageName,
		HelperPath:  strings.TrimSuffix(filePath, filepath.Ext(filePath)) + filepath.Ext(filePath) + "_gen.go",
		AssetPath:   assetPath,
		FuncName:    pascalIdentifier(baseName) + "Script",
		VarName:     lowerFirst(pascalIdentifier(baseName)) + "ScriptOnce",
	}, nil
}

func transformCSSModule(
	layout projectlayout.ProjectLayout,
	filePath string,
	content string,
	classAllocator *generatedClassAllocator,
) ([]cssClass, string, error) {
	mapper := newCSSClassMapper(layout, filePath, classAllocator)
	parser := css.NewParser(parse.NewInputString(content), false)
	streamRewriter := newCSSTokenStreamRewriter(mapper)
	builder := strings.Builder{}
	for {
		grammar, tokenType, data := parser.Next()
		switch grammar {
		case css.ErrorGrammar:
			streamRewriter.flush(&builder)
			err := parser.Err()
			if errors.Is(err, io.EOF) {
				return mapper.classes(), builder.String(), nil
			}
			return nil, "", fmt.Errorf("parse css %q: %w", filePath, err)
		case css.TokenGrammar:
			streamRewriter.write(&builder, tokenType, data)
		case css.CommentGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
		case css.AtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSAtRuleTokens(&builder, data, parser.Values(), mapper)
			builder.WriteByte(';')
		case css.BeginAtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSAtRuleTokens(&builder, data, parser.Values(), mapper)
			builder.WriteByte('{')
		case css.EndAtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.WriteByte('}')
		case css.QualifiedRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSTokens(&builder, parser.Values(), mapper)
			builder.WriteByte(',')
		case css.BeginRulesetGrammar:
			streamRewriter.flush(&builder)
			writeCSSTokens(&builder, parser.Values(), mapper)
			builder.WriteByte('{')
		case css.EndRulesetGrammar:
			streamRewriter.flush(&builder)
			builder.WriteByte('}')
		case css.DeclarationGrammar, css.CustomPropertyGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			builder.WriteByte(':')
			writeRawCSSTokens(&builder, parser.Values())
			builder.WriteByte(';')
		}
	}
}

func writeCSSTokens(builder *strings.Builder, tokens []css.Token, mapper *cssClassMapper) {
	for i := 0; i < len(tokens); i++ {
		token := tokens[i]
		if isCSSClassDot(token) && i+1 < len(tokens) && tokens[i+1].TokenType == css.IdentToken {
			class := mapper.classFor(string(tokens[i+1].Data))
			builder.WriteByte('.')
			builder.WriteString(class.Generated)
			i++
			continue
		}
		builder.Write(token.Data)
	}
}

func writeCSSAtRuleTokens(builder *strings.Builder, name []byte, tokens []css.Token, mapper *cssClassMapper) {
	if atRulePreludeCanContainSelectors(name) {
		writeCSSTokens(builder, tokens, mapper)
		return
	}
	writeRawCSSTokens(builder, tokens)
}

func atRulePreludeCanContainSelectors(name []byte) bool {
	switch strings.ToLower(strings.TrimSpace(string(name))) {
	case "@scope", "@supports":
		return true
	default:
		return false
	}
}

func writeRawCSSTokens(builder *strings.Builder, tokens []css.Token) {
	for _, token := range tokens {
		builder.Write(token.Data)
	}
}

func isCSSClassDot(token css.Token) bool {
	return token.TokenType == css.DelimToken && string(token.Data) == "."
}

func newCSSTokenStreamRewriter(mapper *cssClassMapper) *cssTokenStreamRewriter {
	return &cssTokenStreamRewriter{
		mapper: mapper,
	}
}

func (rewriter *cssTokenStreamRewriter) write(
	builder *strings.Builder,
	tokenType css.TokenType,
	data []byte,
) {
	if rewriter.pendingClassDot {
		if tokenType == css.IdentToken {
			class := rewriter.mapper.classFor(string(data))
			builder.WriteByte('.')
			builder.WriteString(class.Generated)
			rewriter.pendingClassDot = false
			return
		}
		builder.WriteByte('.')
		rewriter.pendingClassDot = false
	}
	if tokenType == css.DelimToken && string(data) == "." {
		rewriter.pendingClassDot = true
		return
	}
	builder.Write(data)
}

func (rewriter *cssTokenStreamRewriter) flush(builder *strings.Builder) {
	if !rewriter.pendingClassDot {
		return
	}
	builder.WriteByte('.')
	rewriter.pendingClassDot = false
}

func newGeneratedClassAllocator() *generatedClassAllocator {
	return &generatedClassAllocator{
		used: map[string]string{},
	}
}

func (allocator *generatedClassAllocator) className(
	layout projectlayout.ProjectLayout,
	filePath string,
	className string,
) string {
	if allocator == nil {
		allocator = newGeneratedClassAllocator()
	}
	key := generatedClassKey(layout, filePath, className)
	base := hashedGeneratedClassName(key)
	candidate := base
	for suffix := 2; ; suffix++ {
		owner, ok := allocator.used[candidate]
		if !ok || owner == key {
			allocator.used[candidate] = key
			return candidate
		}
		candidate = base + "_" + strconv.Itoa(suffix)
	}
}

func newCSSClassMapper(
	layout projectlayout.ProjectLayout,
	filePath string,
	allocator *generatedClassAllocator,
) *cssClassMapper {
	return &cssClassMapper{
		layout:     layout,
		filePath:   filePath,
		allocator:  allocator,
		filePrefix: pascalIdentifier(strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))),
		seen:       map[string]cssClass{},
		constants:  map[string]int{},
	}
}

func (mapper *cssClassMapper) classFor(className string) cssClass {
	if class, ok := mapper.seen[className]; ok {
		return class
	}
	constant := mapper.filePrefix + pascalIdentifier(className) + "Class"
	if count := mapper.constants[constant]; count > 0 {
		constant = constant + strconv.Itoa(count+1)
	}
	mapper.constants[constant]++
	class := cssClass{
		Original:  className,
		Constant:  constant,
		Generated: mapper.allocator.className(mapper.layout, mapper.filePath, className),
	}
	mapper.seen[className] = class
	return class
}

func (mapper *cssClassMapper) classes() []cssClass {
	classNames := make([]string, 0, len(mapper.seen))
	for className := range mapper.seen {
		classNames = append(classNames, className)
	}
	sort.Strings(classNames)
	classes := make([]cssClass, 0, len(classNames))
	for _, className := range classNames {
		classes = append(classes, mapper.seen[className])
	}
	return classes
}

func buildRouteBundle(layout projectlayout.ProjectLayout, index *assetIndex, route RouteSpec) *routeBundle {
	collector := newDependencyCollector(layout, index)
	for _, templatePath := range route.TemplatePaths {
		collector.addFile(templatePath)
	}
	cssFiles := sortedCSSAssets(collector.css)
	scriptFiles := sortedScriptAssets(collector.scripts)
	return &routeBundle{
		RouteID:     route.RouteID,
		CSSFiles:    cssFiles,
		ScriptFiles: scriptFiles,
	}
}

func bundleClientAssets(bundle *routeBundle) metagen.ClientAssets {
	if len(bundle.CSSFiles) > 0 {
		bundle.CSSPath = path.Join("routes", bundle.AssetSlug+".css")
	}
	if len(bundle.ScriptFiles) > 0 {
		bundle.JSPath = path.Join("routes", bundle.AssetSlug+".js")
	}
	assets := metagen.ClientAssets{}
	if bundle.CSSPath != "" {
		assets.Stylesheets = append(assets.Stylesheets, bundle.CSSPath)
	}
	if bundle.JSPath != "" {
		assets.ModuleScripts = append(assets.ModuleScripts, bundle.JSPath)
	}
	return assets
}

type dependencyCollector struct {
	layout       projectlayout.ProjectLayout
	index        *assetIndex
	visitedFiles map[string]struct{}
	visitedDirs  map[string]struct{}
	css          map[*cssAsset]struct{}
	scripts      map[*scriptAsset]struct{}
}

func newDependencyCollector(layout projectlayout.ProjectLayout, index *assetIndex) *dependencyCollector {
	return &dependencyCollector{
		layout:       layout,
		index:        index,
		visitedFiles: map[string]struct{}{},
		visitedDirs:  map[string]struct{}{},
		css:          map[*cssAsset]struct{}{},
		scripts:      map[*scriptAsset]struct{}{},
	}
}

func (collector *dependencyCollector) addFile(filePath string) {
	cleanPath := filepath.Clean(filePath)
	if _, ok := collector.visitedFiles[cleanPath]; ok {
		return
	}
	collector.visitedFiles[cleanPath] = struct{}{}
	collector.addFileAssets(cleanPath)

	content, err := os.ReadFile(cleanPath)
	if err != nil {
		return
	}
	for _, importPath := range quotedImports(string(content)) {
		if dir, ok := collector.componentDirForImport(importPath); ok {
			collector.addDir(dir)
			collector.scanPackageFiles(dir)
		}
	}
}

func (collector *dependencyCollector) addFileAssets(filePath string) {
	stem := strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
	if stem == "" {
		return
	}

	dir := filepath.Dir(filepath.Clean(filePath))
	for _, asset := range collector.index.cssByDir[dir] {
		if assetStem(asset.SourcePath) == stem {
			collector.css[asset] = struct{}{}
		}
	}
	for _, asset := range collector.index.scriptByDir[dir] {
		if assetStem(asset.SourcePath) == stem {
			collector.scripts[asset] = struct{}{}
		}
	}
}

func (collector *dependencyCollector) addDir(dir string) {
	cleanDir := filepath.Clean(dir)
	if _, ok := collector.visitedDirs[cleanDir]; ok {
		return
	}
	collector.visitedDirs[cleanDir] = struct{}{}
	for _, asset := range collector.index.cssByDir[cleanDir] {
		collector.css[asset] = struct{}{}
	}
	for _, asset := range collector.index.scriptByDir[cleanDir] {
		collector.scripts[asset] = struct{}{}
	}
}

func (collector *dependencyCollector) scanPackageFiles(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) != ".templ" && filepath.Ext(name) != ".go" {
			continue
		}
		if strings.HasSuffix(name, "_test.go") || isGeneratedHelper(name) {
			continue
		}
		collector.addFile(filepath.Join(dir, name))
	}
}

func (collector *dependencyCollector) componentDirForImport(importPath string) (string, bool) {
	prefix := path.Join(collector.layout.AppModulePath, componentsImportPath(collector.layout))
	trimmed := strings.TrimSpace(importPath)
	if trimmed != prefix && !strings.HasPrefix(trimmed, prefix+"/") {
		return "", false
	}
	relative := strings.TrimPrefix(trimmed, prefix)
	relative = strings.TrimPrefix(relative, "/")
	return filepath.Join(componentsDir(collector.layout), filepath.FromSlash(relative)), true
}

func DiscoverRouteSpecs(layout projectlayout.ProjectLayout) ([]RouteSpec, error) {
	root := strings.TrimSpace(layout.RoutesDir)
	if root == "" {
		return nil, fmt.Errorf("routes dir is required")
	}
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	layoutByRoute := map[string]string{}
	pages := map[string]string{}
	rootTemplate := ""
	if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		name := entry.Name()
		if name != "root.templ" && name != "layout.templ" && name != "page.templ" {
			return nil
		}
		routeID, err := routeIDForDir(root, filepath.Dir(filePath))
		if err != nil {
			return err
		}
		switch name {
		case "root.templ":
			rootTemplate = filePath
		case "layout.templ":
			layoutByRoute[routeID] = filePath
		case "page.templ":
			pages[routeID] = filePath
		}
		return nil
	}); err != nil {
		return nil, err
	}

	routeIDs := make([]string, 0, len(pages))
	for routeID := range pages {
		routeIDs = append(routeIDs, routeID)
	}
	sort.Strings(routeIDs)
	routes := make([]RouteSpec, 0, len(routeIDs))
	for _, routeID := range routeIDs {
		templates := []string{}
		if strings.TrimSpace(rootTemplate) != "" {
			templates = append(templates, rootTemplate)
		}
		templates = append(templates, layoutTemplateChain(routeID, layoutByRoute)...)
		templates = append(templates, pages[routeID])
		routes = append(routes, RouteSpec{RouteID: routeID, TemplatePaths: templates})
	}
	return routes, nil
}

func DiscoverNotFoundSpecs(layout projectlayout.ProjectLayout) ([]RouteSpec, error) {
	root := strings.TrimSpace(layout.RoutesDir)
	if root == "" {
		return nil, fmt.Errorf("routes dir is required")
	}
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	layoutByRoute := map[string]string{}
	notFounds := map[string]string{}
	rootTemplate := ""
	if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		name := entry.Name()
		if name != "root.templ" && name != "layout.templ" && name != "404.templ" {
			return nil
		}
		routeID, err := routeIDForDir(root, filepath.Dir(filePath))
		if err != nil {
			return err
		}
		switch name {
		case "root.templ":
			rootTemplate = filePath
		case "layout.templ":
			layoutByRoute[routeID] = filePath
		case "404.templ":
			notFounds[routeID] = filePath
		}
		return nil
	}); err != nil {
		return nil, err
	}

	routeIDs := make([]string, 0, len(notFounds))
	for routeID := range notFounds {
		routeIDs = append(routeIDs, routeID)
	}
	sort.Strings(routeIDs)
	routes := make([]RouteSpec, 0, len(routeIDs))
	for _, routeID := range routeIDs {
		templates := []string{}
		if strings.TrimSpace(rootTemplate) != "" {
			templates = append(templates, rootTemplate)
		}
		templates = append(templates, layoutTemplateChain(routeID, layoutByRoute)...)
		templates = append(templates, notFounds[routeID])
		routes = append(routes, RouteSpec{RouteID: routeID, TemplatePaths: templates})
	}
	return routes, nil
}

func layoutTemplateChain(routeID string, layoutByRoute map[string]string) []string {
	segments := []string{}
	if strings.TrimSpace(routeID) != "" {
		segments = strings.Split(routeID, "/")
	}
	candidates := []string{""}
	for idx := 1; idx <= len(segments); idx++ {
		candidates = append(candidates, strings.Join(segments[:idx], "/"))
	}
	templates := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		if filePath := layoutByRoute[candidate]; strings.TrimSpace(filePath) != "" {
			templates = append(templates, filePath)
		}
	}
	return templates
}

func routeIDForDir(root string, dir string) (string, error) {
	relative, err := filepath.Rel(root, dir)
	if err != nil {
		return "", err
	}
	relative = filepath.ToSlash(relative)
	if relative == "." {
		relative = ""
	}
	rawSegments, err := frameworkrouter.ParseDirectorySegments(relative)
	if err != nil {
		return "", err
	}
	parts := make([]string, 0, len(rawSegments))
	for _, segment := range rawSegments {
		parts = append(parts, segment.RawPart())
	}
	return strings.Join(parts, "/"), nil
}

func writeStaticOutputs(stageDir string, plan Plan) error {
	for _, script := range plan.scriptFiles {
		if err := writeScriptBundle(stageDir, script.AssetPath, []*scriptAsset{script}); err != nil {
			return err
		}
	}
	for _, route := range plan.routes {
		if route.CSSPath != "" {
			if err := writeCSSBundle(stageDir, route.CSSPath, route.CSSFiles); err != nil {
				return err
			}
		}
		if route.JSPath != "" {
			if err := writeScriptBundle(stageDir, route.JSPath, route.ScriptFiles); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeCSSBundle(stageDir string, assetPath string, files []*cssAsset) error {
	if len(files) == 0 {
		return nil
	}
	builder := strings.Builder{}
	for _, file := range files {
		if strings.TrimSpace(file.Transformed) == "" {
			continue
		}
		if builder.Len() > 0 {
			builder.WriteByte('\n')
		}
		builder.WriteString(file.Transformed)
		builder.WriteByte('\n')
	}
	if strings.TrimSpace(builder.String()) == "" {
		return nil
	}
	return writeStageFile(stageDir, assetPath, []byte(builder.String()))
}

func writeScriptBundle(stageDir string, assetPath string, files []*scriptAsset) error {
	if len(files) == 0 {
		return nil
	}
	imports := strings.Builder{}
	for _, file := range files {
		imports.WriteString("import ")
		imports.WriteString(strconv.Quote(filepath.ToSlash(file.SourcePath)))
		imports.WriteString(";\n")
	}
	result := api.Build(api.BuildOptions{
		Stdin: &api.StdinOptions{
			Contents:   imports.String(),
			ResolveDir: filepath.Dir(files[0].SourcePath),
			Sourcefile: "no-js-client-assets-entry.js",
			Loader:     api.LoaderJS,
		},
		Bundle:            true,
		Write:             false,
		Format:            api.FormatESModule,
		Platform:          api.PlatformBrowser,
		Target:            api.ES2020,
		MinifyWhitespace:  true,
		MinifySyntax:      true,
		MinifyIdentifiers: true,
	})
	if len(result.Errors) > 0 {
		return fmt.Errorf("bundle client script %q: %s", assetPath, result.Errors[0].Text)
	}
	if len(result.OutputFiles) == 0 {
		return nil
	}
	return writeStageFile(stageDir, assetPath, result.OutputFiles[0].Contents)
}

func writeStageFile(stageDir string, assetPath string, content []byte) error {
	target := filepath.Join(stageDir, filepath.FromSlash(strings.TrimLeft(assetPath, "/")))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create asset dir for %q: %w", target, err)
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		return fmt.Errorf("write asset %q: %w", target, err)
	}
	return nil
}

func writeCSSHelper(asset *cssAsset) error {
	builder := strings.Builder{}
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage ")
	builder.WriteString(asset.PackageName)
	builder.WriteString("\n\n")
	if len(asset.Classes) > 0 {
		builder.WriteString("const (\n")
		for _, class := range asset.Classes {
			builder.WriteString("\t")
			builder.WriteString(class.Constant)
			builder.WriteString(" = ")
			builder.WriteString(strconv.Quote(class.Generated))
			builder.WriteString("\n")
		}
		builder.WriteString(")\n")
	}
	return os.WriteFile(asset.HelperPath, []byte(builder.String()), 0o644)
}

func writeScriptHelper(asset *scriptAsset) error {
	builder := strings.Builder{}
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage ")
	builder.WriteString(asset.PackageName)
	builder.WriteString(`

import (
	"context"
	"html"
	"io"

	"github.com/RevoTale/no-js/framework/metagen"
	"github.com/a-h/templ"
)

var `)
	builder.WriteString(asset.VarName)
	builder.WriteString(" = templ.NewOnceHandle(templ.WithComponent(templ.ComponentFunc(\n")
	builder.WriteString("\tfunc(ctx context.Context, w io.Writer) error {\n")
	builder.WriteString("\tsrc := metagen.AssetURL(ctx, ")
	builder.WriteString(strconv.Quote(asset.AssetPath))
	builder.WriteString(")\n")
	builder.WriteString("\tif src == \"\" {\n\t\treturn nil\n\t}\n")
	builder.WriteString("\t_, err := io.WriteString(w, `<script type=\"module\" src=\"`+\n")
	builder.WriteString("\t\thtml.EscapeString(src)+`\"></script>`)\n")
	builder.WriteString("\treturn err\n})))\n\n")
	builder.WriteString("func ")
	builder.WriteString(asset.FuncName)
	builder.WriteString("() templ.Component {\n\treturn ")
	builder.WriteString(asset.VarName)
	builder.WriteString(".Once()\n}\n")
	return os.WriteFile(asset.HelperPath, []byte(builder.String()), 0o644)
}

func packageNameForDir(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf("read package dir %q: %w", dir, err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) == ".templ" {
			files = append(files, filepath.Join(dir, name))
		}
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) != ".go" || strings.HasSuffix(name, "_test.go") || isGeneratedHelper(name) {
			continue
		}
		files = append(files, filepath.Join(dir, name))
	}
	for _, filePath := range files {
		content, readErr := os.ReadFile(filePath)
		if readErr != nil {
			return "", readErr
		}
		match := packageRE.FindSubmatch(content)
		if len(match) >= 2 {
			return string(match[1]), nil
		}
	}
	return "", fmt.Errorf("no Go package declaration found in %q", dir)
}

func cleanGeneratedHelpers(layout projectlayout.ProjectLayout) error {
	for _, root := range clientAssetRoots(layout) {
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return err
		}
		if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			if !isGeneratedHelper(filePath) {
				return nil
			}
			content, readErr := os.ReadFile(filePath)
			if readErr != nil {
				return readErr
			}
			if strings.HasPrefix(string(content), generatedHeader) {
				return os.Remove(filePath)
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func clientAssetRoots(layout projectlayout.ProjectLayout) []string {
	roots := []string{}
	if strings.TrimSpace(layout.RoutesDir) != "" {
		roots = append(roots, layout.RoutesDir)
	}
	componentRoot := componentsDir(layout)
	if strings.TrimSpace(componentRoot) != "" {
		roots = append(roots, componentRoot)
	}
	return roots
}

func componentsDir(layout projectlayout.ProjectLayout) string {
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return ""
	}
	return filepath.Join(filepath.Dir(layout.RoutesDir), "components")
}

func componentsImportPath(layout projectlayout.ProjectLayout) string {
	routesImport := strings.Trim(strings.TrimSpace(layout.RoutesImport), "/")
	if routesImport == "" {
		return "components"
	}
	return path.Join(path.Dir(routesImport), "components")
}

func logicalScriptAssetPath(layout projectlayout.ProjectLayout, filePath string) (string, error) {
	webRoot := filepath.Dir(layout.RoutesDir)
	relative, err := filepath.Rel(webRoot, filePath)
	if err != nil || strings.HasPrefix(relative, "..") {
		relative, err = filepath.Rel(layout.RootDir, filePath)
		if err != nil {
			return "", err
		}
	}
	relative = filepath.ToSlash(relative)
	ext := path.Ext(relative)
	return strings.TrimSuffix(relative, ext) + ".js", nil
}

func quotedImports(content string) []string {
	matches := quotedImportRE.FindAllStringSubmatch(content, -1)
	imports := make([]string, 0, len(matches))
	for _, match := range matches {
		if len(match) >= 2 {
			imports = append(imports, strings.TrimSpace(match[1]))
		}
	}
	return imports
}

func sortedCSSAssets(values map[*cssAsset]struct{}) []*cssAsset {
	out := make([]*cssAsset, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Slice(out, func(i int, j int) bool { return out[i].SourcePath < out[j].SourcePath })
	return out
}

func sortedScriptAssets(values map[*scriptAsset]struct{}) []*scriptAsset {
	out := make([]*scriptAsset, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Slice(out, func(i int, j int) bool { return out[i].SourcePath < out[j].SourcePath })
	return out
}

func assetStem(filePath string) string {
	return strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
}

func generatedClassKey(layout projectlayout.ProjectLayout, filePath string, className string) string {
	relative, err := filepath.Rel(layout.RootDir, filePath)
	if err != nil {
		relative = filePath
	}
	return filepath.ToSlash(relative) + "\x00" + className
}

func hashedGeneratedClassName(key string) string {
	hash := sha1.Sum([]byte(key))
	encoded := hex.EncodeToString(hash[:])
	return "n_" + encoded[:8]
}

func notFoundAssetSlug(routeID string) string {
	if strings.TrimSpace(routeID) == "" {
		return "404"
	}
	return assetSlug(routeID) + "_404"
}

func assetSlug(routeID string) string {
	trimmed := strings.Trim(strings.TrimSpace(routeID), "/")
	if trimmed == "" {
		return "index"
	}
	builder := strings.Builder{}
	for _, r := range trimmed {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			builder.WriteRune(r)
		case r == '-' || r == '_':
			builder.WriteRune(r)
		default:
			builder.WriteByte('_')
		}
	}
	return strings.Trim(builder.String(), "_")
}

func pascalIdentifier(value string) string {
	builder := strings.Builder{}
	capitalize := true
	for _, r := range value {
		if r == '-' || r == '_' || r == '.' || r == ' ' {
			capitalize = true
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			capitalize = true
			continue
		}
		if builder.Len() == 0 && unicode.IsDigit(r) {
			builder.WriteString("X")
		}
		if capitalize {
			builder.WriteRune(unicode.ToUpper(r))
			capitalize = false
		} else {
			builder.WriteRune(r)
		}
	}
	if builder.Len() == 0 {
		return "Asset"
	}
	return builder.String()
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	r, size := utf8.DecodeRuneInString(value)
	if r == utf8.RuneError && size == 0 {
		return value
	}
	return string(unicode.ToLower(r)) + value[size:]
}

func shouldSkipDir(dir string, layout projectlayout.ProjectLayout) bool {
	clean := filepath.Clean(dir)
	for _, skip := range []string{layout.GeneratedDir, layout.StaticAssets.OutDir, layout.StaticAssets.SourceDir} {
		if strings.TrimSpace(skip) == "" {
			continue
		}
		if clean == filepath.Clean(skip) {
			return true
		}
	}
	base := filepath.Base(clean)
	return strings.HasPrefix(base, ".") || base == "node_modules"
}

func isCSSFile(filePath string) bool {
	return strings.EqualFold(filepath.Ext(filePath), ".css")
}

func isScriptFile(filePath string) bool {
	ext := strings.ToLower(filepath.Ext(filePath))
	switch ext {
	case ".js", ".ts", ".mjs", ".mts":
		return true
	default:
		return false
	}
}

func isGeneratedHelper(filePath string) bool {
	name := filepath.Base(filePath)
	return strings.HasSuffix(name, ".css_gen.go") ||
		strings.HasSuffix(name, ".js_gen.go") ||
		strings.HasSuffix(name, ".ts_gen.go") ||
		strings.HasSuffix(name, ".mjs_gen.go") ||
		strings.HasSuffix(name, ".mts_gen.go")
}

func isSkipAll(err error) bool {
	return err == fs.SkipAll
}
