package clientassets

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/RevoTale/no-js/framework/metagen"
	"github.com/RevoTale/no-js/internal/filesystem"
	"github.com/RevoTale/no-js/internal/projectlayout"
)

const generatedHeader = "// Code generated by cmd/no-js client assets. DO NOT EDIT."

type Config struct {
	Layout projectlayout.ProjectLayout
	Routes []RouteSpec
}

type PrepareStaticSourceConfig struct {
	Layout    projectlayout.ProjectLayout
	SourceDir string
}

type RouteSpec struct {
	RouteID       string
	TemplatePaths []string
	CSSBundles    []CSSBundleSpec
}

type CSSBundleSpec struct {
	OwnerTemplatePath string
	TemplatePaths     []string
}

type Plan struct {
	RouteAssets    map[string]metagen.ClientAssets
	NotFoundAssets map[string]metagen.ClientAssets

	cssFiles    []*cssAsset
	cssBundles  []*cssBundle
	scriptFiles []*scriptAsset
}

type cssAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	AssetPath   string
	Transformed string
	Classes     []cssClass
}

type cssClass struct {
	Original  string
	Constant  string
	Generated string
}

type scriptAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	AssetPath   string
	FuncName    string
	VarName     string
}

type routeBundle struct {
	RouteID        string
	CSSBundlePaths []string
	ScriptFiles    []*scriptAsset
}

type cssBundle struct {
	AssetPath string
	CSSFiles  []*cssAsset
}

type assetIndex struct {
	cssByDir    map[string][]*cssAsset
	scriptByDir map[string][]*scriptAsset
	cssFiles    []*cssAsset
	scriptFiles []*scriptAsset
}

type generatedClassAllocator struct {
	used map[string]string
}

type cssClassMapper struct {
	layout     projectlayout.ProjectLayout
	filePath   string
	allocator  *generatedClassAllocator
	filePrefix string
	seen       map[string]cssClass
	constants  map[string]int
}

type cssTokenStreamRewriter struct {
	mapper          *cssClassMapper
	pendingClassDot bool
}

func Generate(cfg Config) (Plan, error) {
	plan, err := BuildPlan(cfg)
	if err != nil {
		return Plan{}, err
	}
	if err := cleanGeneratedHelpers(cfg.Layout); err != nil {
		return Plan{}, err
	}
	for _, css := range plan.cssFiles {
		if err := writeCSSHelper(css); err != nil {
			return Plan{}, err
		}
	}
	for _, script := range plan.scriptFiles {
		if err := writeScriptHelper(script); err != nil {
			return Plan{}, err
		}
	}
	return plan.public(), nil
}

func BuildPlan(cfg Config) (Plan, error) {
	layout := cfg.Layout
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return Plan{}, fmt.Errorf("routes dir is required")
	}

	routes := cfg.Routes
	if len(routes) == 0 {
		discovered, err := DiscoverRouteSpecs(layout)
		if err != nil {
			return Plan{}, err
		}
		routes = discovered
	}

	index, err := discoverAssets(layout)
	if err != nil {
		return Plan{}, err
	}

	notFounds, err := DiscoverNotFoundSpecs(layout)
	if err != nil {
		return Plan{}, err
	}

	cssBundlesByPath := map[string]*cssBundle{}
	cssBundleOrder := []string{}
	routeBundles := make(map[string]*routeBundle, len(routes))
	for _, route := range routes {
		bundle, cssBundles, err := buildRouteBundle(layout, index, route)
		if err != nil {
			return Plan{}, err
		}
		routeBundles[route.RouteID] = bundle
		mergeCSSBundles(cssBundlesByPath, &cssBundleOrder, cssBundles)
	}

	notFoundBundles := make(map[string]*routeBundle, len(notFounds))
	for _, notFound := range notFounds {
		bundle, cssBundles, err := buildRouteBundle(layout, index, notFound)
		if err != nil {
			return Plan{}, err
		}
		notFoundBundles[notFound.RouteID] = bundle
		mergeCSSBundles(cssBundlesByPath, &cssBundleOrder, cssBundles)
	}

	cssBundles := make([]*cssBundle, 0, len(cssBundleOrder))
	for _, assetPath := range cssBundleOrder {
		cssBundles = append(cssBundles, cssBundlesByPath[assetPath])
	}

	return Plan{
		RouteAssets:    bundleClientAssetsByRoute(routeBundles, cssBundlesByPath),
		NotFoundAssets: bundleClientAssetsByRoute(notFoundBundles, cssBundlesByPath),
		cssFiles:       index.cssFiles,
		cssBundles:     cssBundles,
		scriptFiles:    index.scriptFiles,
	}, nil
}

func HasClientAssets(layout projectlayout.ProjectLayout) (bool, error) {
	roots := clientAssetRoots(layout)
	for _, root := range roots {
		if strings.TrimSpace(root) == "" {
			continue
		}
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return false, err
		}
		found := false
		err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				if shouldSkipDir(filePath, layout) && filePath != root {
					return fs.SkipDir
				}
				return nil
			}
			if isCSSFile(filePath) || isScriptFile(filePath) {
				found = true
				return fs.SkipAll
			}
			return nil
		})
		if err != nil && !isSkipAll(err) {
			return false, err
		}
		if found {
			return true, nil
		}
	}
	return false, nil
}

func PrepareStaticSource(cfg PrepareStaticSourceConfig) (string, func() error, error) {
	layout := cfg.Layout
	stageDir, err := os.MkdirTemp("", "no-js-client-assets-*")
	if err != nil {
		return "", nil, fmt.Errorf("create client assets stage: %w", err)
	}
	cleanup := func() error { return os.RemoveAll(stageDir) }

	if strings.TrimSpace(cfg.SourceDir) != "" {
		if info, statErr := os.Stat(cfg.SourceDir); statErr == nil && info.IsDir() {
			if err := filesystem.CopyTree(cfg.SourceDir, stageDir); err != nil {
				_ = cleanup()
				return "", nil, fmt.Errorf("copy static source: %w", err)
			}
		} else if statErr != nil && !os.IsNotExist(statErr) {
			_ = cleanup()
			return "", nil, fmt.Errorf("stat static source: %w", statErr)
		}
	}

	plan, err := BuildPlan(Config{Layout: layout})
	if err != nil {
		_ = cleanup()
		return "", nil, err
	}
	if err := writeStaticOutputs(stageDir, layout, plan); err != nil {
		_ = cleanup()
		return "", nil, err
	}
	return stageDir, cleanup, nil
}

func (plan Plan) public() Plan {
	out := Plan{
		RouteAssets:    map[string]metagen.ClientAssets{},
		NotFoundAssets: map[string]metagen.ClientAssets{},
	}
	for routeID, assets := range plan.RouteAssets {
		out.RouteAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	for routeID, assets := range plan.NotFoundAssets {
		out.NotFoundAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	return out
}
