package clientassets

import (
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/RevoTale/no-js/framework/metagen"
	frameworkrouter "github.com/RevoTale/no-js/framework/router"
	"github.com/RevoTale/no-js/internal/bundler/clientassetext"
	"github.com/RevoTale/no-js/internal/filesystem"
	"github.com/RevoTale/no-js/internal/projectlayout"
	"github.com/evanw/esbuild/pkg/api"
	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/css"
)

const generatedHeader = "// Code generated by cmd/no-js client assets. DO NOT EDIT."

var (
	packageRE      = regexp.MustCompile(`(?m)^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)`)
	quotedImportRE = regexp.MustCompile(`"([^"]+)"`)
)

type Config struct {
	Layout projectlayout.ProjectLayout
	Routes []RouteSpec
}

type PrepareStaticSourceConfig struct {
	Layout    projectlayout.ProjectLayout
	SourceDir string
}

type RouteSpec struct {
	RouteID       string
	TemplatePaths []string
	CSSBundles    []CSSBundleSpec
}

type CSSBundleSpec struct {
	OwnerTemplatePath string
	TemplatePaths     []string
}

type Plan struct {
	RouteAssets    map[string]metagen.ClientAssets
	NotFoundAssets map[string]metagen.ClientAssets

	cssFiles    []*cssAsset
	cssBundles  []*cssBundle
	scriptFiles []*scriptAsset
}

type cssAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	AssetPath   string
	Transformed string
	Classes     []cssClass
}

type cssClass struct {
	Original  string
	Constant  string
	Generated string
}

type scriptAsset struct {
	SourcePath  string
	PackageDir  string
	PackageName string
	HelperPath  string
	AssetPath   string
	FuncName    string
	VarName     string
}

type routeBundle struct {
	RouteID        string
	CSSBundlePaths []string
	ScriptFiles    []*scriptAsset
}

type cssBundle struct {
	AssetPath string
	CSSFiles  []*cssAsset
}

type assetIndex struct {
	cssByDir    map[string][]*cssAsset
	scriptByDir map[string][]*scriptAsset
	cssFiles    []*cssAsset
	scriptFiles []*scriptAsset
}

type generatedClassAllocator struct {
	used map[string]string
}

type cssClassMapper struct {
	layout     projectlayout.ProjectLayout
	filePath   string
	allocator  *generatedClassAllocator
	filePrefix string
	seen       map[string]cssClass
	constants  map[string]int
}

type cssTokenStreamRewriter struct {
	mapper          *cssClassMapper
	pendingClassDot bool
}

func Generate(cfg Config) (Plan, error) {
	plan, err := BuildPlan(cfg)
	if err != nil {
		return Plan{}, err
	}
	if err := cleanGeneratedHelpers(cfg.Layout); err != nil {
		return Plan{}, err
	}
	for _, css := range plan.cssFiles {
		if err := writeCSSHelper(css); err != nil {
			return Plan{}, err
		}
	}
	for _, script := range plan.scriptFiles {
		if err := writeScriptHelper(script); err != nil {
			return Plan{}, err
		}
	}
	return plan.public(), nil
}

func BuildPlan(cfg Config) (Plan, error) {
	layout := cfg.Layout
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return Plan{}, fmt.Errorf("routes dir is required")
	}

	routes := cfg.Routes
	if len(routes) == 0 {
		discovered, err := DiscoverRouteSpecs(layout)
		if err != nil {
			return Plan{}, err
		}
		routes = discovered
	}

	index, err := discoverAssets(layout)
	if err != nil {
		return Plan{}, err
	}

	notFounds, err := DiscoverNotFoundSpecs(layout)
	if err != nil {
		return Plan{}, err
	}

	cssBundlesByPath := map[string]*cssBundle{}
	cssBundleOrder := []string{}
	routeBundles := make(map[string]*routeBundle, len(routes))
	for _, route := range routes {
		bundle, cssBundles, err := buildRouteBundle(layout, index, route)
		if err != nil {
			return Plan{}, err
		}
		routeBundles[route.RouteID] = bundle
		mergeCSSBundles(cssBundlesByPath, &cssBundleOrder, cssBundles)
	}

	notFoundBundles := make(map[string]*routeBundle, len(notFounds))
	for _, notFound := range notFounds {
		bundle, cssBundles, err := buildRouteBundle(layout, index, notFound)
		if err != nil {
			return Plan{}, err
		}
		notFoundBundles[notFound.RouteID] = bundle
		mergeCSSBundles(cssBundlesByPath, &cssBundleOrder, cssBundles)
	}

	cssBundles := make([]*cssBundle, 0, len(cssBundleOrder))
	for _, assetPath := range cssBundleOrder {
		cssBundles = append(cssBundles, cssBundlesByPath[assetPath])
	}

	return Plan{
		RouteAssets:    bundleClientAssetsByRoute(routeBundles, cssBundlesByPath),
		NotFoundAssets: bundleClientAssetsByRoute(notFoundBundles, cssBundlesByPath),
		cssFiles:       index.cssFiles,
		cssBundles:     cssBundles,
		scriptFiles:    index.scriptFiles,
	}, nil
}

func HasClientAssets(layout projectlayout.ProjectLayout) (bool, error) {
	roots := clientAssetRoots(layout)
	for _, root := range roots {
		if strings.TrimSpace(root) == "" {
			continue
		}
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return false, err
		}
		found := false
		err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				if shouldSkipDir(filePath, layout) && filePath != root {
					return fs.SkipDir
				}
				return nil
			}
			if isCSSFile(filePath) || isScriptFile(filePath) {
				found = true
				return fs.SkipAll
			}
			return nil
		})
		if err != nil && !isSkipAll(err) {
			return false, err
		}
		if found {
			return true, nil
		}
	}
	return false, nil
}

func PrepareStaticSource(cfg PrepareStaticSourceConfig) (string, func() error, error) {
	layout := cfg.Layout
	stageDir, err := os.MkdirTemp("", "no-js-client-assets-*")
	if err != nil {
		return "", nil, fmt.Errorf("create client assets stage: %w", err)
	}
	cleanup := func() error { return os.RemoveAll(stageDir) }

	if strings.TrimSpace(cfg.SourceDir) != "" {
		if info, statErr := os.Stat(cfg.SourceDir); statErr == nil && info.IsDir() {
			if err := filesystem.CopyTree(cfg.SourceDir, stageDir); err != nil {
				_ = cleanup()
				return "", nil, fmt.Errorf("copy static source: %w", err)
			}
		} else if statErr != nil && !os.IsNotExist(statErr) {
			_ = cleanup()
			return "", nil, fmt.Errorf("stat static source: %w", statErr)
		}
	}

	plan, err := BuildPlan(Config{Layout: layout})
	if err != nil {
		_ = cleanup()
		return "", nil, err
	}
	if err := writeStaticOutputs(stageDir, layout, plan); err != nil {
		_ = cleanup()
		return "", nil, err
	}
	return stageDir, cleanup, nil
}

func (plan Plan) public() Plan {
	out := Plan{
		RouteAssets:    map[string]metagen.ClientAssets{},
		NotFoundAssets: map[string]metagen.ClientAssets{},
	}
	for routeID, assets := range plan.RouteAssets {
		out.RouteAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	for routeID, assets := range plan.NotFoundAssets {
		out.NotFoundAssets[routeID] = metagen.ClientAssets{
			Stylesheets:   append([]string(nil), assets.Stylesheets...),
			ModuleScripts: append([]string(nil), assets.ModuleScripts...),
		}
	}
	return out
}

func discoverAssets(layout projectlayout.ProjectLayout) (*assetIndex, error) {
	index := &assetIndex{
		cssByDir:    map[string][]*cssAsset{},
		scriptByDir: map[string][]*scriptAsset{},
	}
	classAllocator := newGeneratedClassAllocator()
	for _, root := range clientAssetRoots(layout) {
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("stat client asset root %q: %w", root, err)
		}
		if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				if shouldSkipDir(filePath, layout) && filePath != root {
					return fs.SkipDir
				}
				return nil
			}
			if isGeneratedHelper(filePath) {
				return nil
			}
			switch {
			case isCSSFile(filePath):
				asset, err := newCSSAsset(layout, filePath, classAllocator)
				if err != nil {
					return err
				}
				index.cssByDir[asset.PackageDir] = append(index.cssByDir[asset.PackageDir], asset)
				index.cssFiles = append(index.cssFiles, asset)
			case isScriptFile(filePath):
				asset, err := newScriptAsset(layout, filePath)
				if err != nil {
					return err
				}
				index.scriptByDir[asset.PackageDir] = append(index.scriptByDir[asset.PackageDir], asset)
				index.scriptFiles = append(index.scriptFiles, asset)
			}
			return nil
		}); err != nil {
			return nil, err
		}
	}

	sort.Slice(index.cssFiles, func(i int, j int) bool {
		return index.cssFiles[i].SourcePath < index.cssFiles[j].SourcePath
	})
	sort.Slice(index.scriptFiles, func(i int, j int) bool {
		return index.scriptFiles[i].SourcePath < index.scriptFiles[j].SourcePath
	})
	return index, nil
}

func newCSSAsset(
	layout projectlayout.ProjectLayout,
	filePath string,
	classAllocator *generatedClassAllocator,
) (*cssAsset, error) {
	packageName, err := packageNameForDir(filepath.Dir(filePath))
	if err != nil {
		return nil, err
	}
	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read css %q: %w", filePath, err)
	}
	classes, transformed, err := transformCSSModule(layout, filePath, string(content), classAllocator)
	if err != nil {
		return nil, err
	}
	assetPath, err := logicalCSSAssetPath(layout, filePath)
	if err != nil {
		return nil, err
	}
	return &cssAsset{
		SourcePath:  filePath,
		PackageDir:  filepath.Dir(filePath),
		PackageName: packageName,
		HelperPath:  strings.TrimSuffix(filePath, ".css") + ".css_gen.go",
		AssetPath:   assetPath,
		Transformed: transformed,
		Classes:     classes,
	}, nil
}

func newScriptAsset(layout projectlayout.ProjectLayout, filePath string) (*scriptAsset, error) {
	packageName, err := packageNameForDir(filepath.Dir(filePath))
	if err != nil {
		return nil, err
	}
	baseName := strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
	assetPath, err := logicalScriptAssetPath(layout, filePath)
	if err != nil {
		return nil, err
	}
	return &scriptAsset{
		SourcePath:  filePath,
		PackageDir:  filepath.Dir(filePath),
		PackageName: packageName,
		HelperPath:  strings.TrimSuffix(filePath, filepath.Ext(filePath)) + filepath.Ext(filePath) + "_gen.go",
		AssetPath:   assetPath,
		FuncName:    pascalIdentifier(baseName) + "Script",
		VarName:     lowerFirst(pascalIdentifier(baseName)) + "ScriptOnce",
	}, nil
}

func transformCSSModule(
	layout projectlayout.ProjectLayout,
	filePath string,
	content string,
	classAllocator *generatedClassAllocator,
) ([]cssClass, string, error) {
	mapper := newCSSClassMapper(layout, filePath, classAllocator)
	parser := css.NewParser(parse.NewInputString(content), false)
	streamRewriter := newCSSTokenStreamRewriter(mapper)
	builder := strings.Builder{}
	for {
		grammar, tokenType, data := parser.Next()
		switch grammar {
		case css.ErrorGrammar:
			streamRewriter.flush(&builder)
			err := parser.Err()
			if errors.Is(err, io.EOF) {
				return mapper.classes(), builder.String(), nil
			}
			return nil, "", fmt.Errorf("parse css %q: %w", filePath, err)
		case css.TokenGrammar:
			streamRewriter.write(&builder, tokenType, data)
		case css.CommentGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
		case css.AtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSAtRuleTokens(&builder, data, parser.Values(), mapper)
			builder.WriteByte(';')
		case css.BeginAtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSAtRuleTokens(&builder, data, parser.Values(), mapper)
			builder.WriteByte('{')
		case css.EndAtRuleGrammar:
			streamRewriter.flush(&builder)
			builder.WriteByte('}')
		case css.QualifiedRuleGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			writeCSSTokens(&builder, parser.Values(), mapper)
			builder.WriteByte(',')
		case css.BeginRulesetGrammar:
			streamRewriter.flush(&builder)
			writeCSSTokens(&builder, parser.Values(), mapper)
			builder.WriteByte('{')
		case css.EndRulesetGrammar:
			streamRewriter.flush(&builder)
			builder.WriteByte('}')
		case css.DeclarationGrammar, css.CustomPropertyGrammar:
			streamRewriter.flush(&builder)
			builder.Write(data)
			builder.WriteByte(':')
			writeRawCSSTokens(&builder, parser.Values())
			builder.WriteByte(';')
		}
	}
}

func writeCSSTokens(builder *strings.Builder, tokens []css.Token, mapper *cssClassMapper) {
	for i := 0; i < len(tokens); i++ {
		token := tokens[i]
		if isCSSClassDot(token) && i+1 < len(tokens) && tokens[i+1].TokenType == css.IdentToken {
			class := mapper.classFor(string(tokens[i+1].Data))
			builder.WriteByte('.')
			builder.WriteString(class.Generated)
			i++
			continue
		}
		builder.Write(token.Data)
	}
}

func writeCSSAtRuleTokens(builder *strings.Builder, name []byte, tokens []css.Token, mapper *cssClassMapper) {
	if atRulePreludeCanContainSelectors(name) {
		writeCSSTokens(builder, tokens, mapper)
		return
	}
	writeRawCSSTokens(builder, tokens)
}

func atRulePreludeCanContainSelectors(name []byte) bool {
	switch strings.ToLower(strings.TrimSpace(string(name))) {
	case "@scope", "@supports":
		return true
	default:
		return false
	}
}

func writeRawCSSTokens(builder *strings.Builder, tokens []css.Token) {
	for _, token := range tokens {
		builder.Write(token.Data)
	}
}

func isCSSClassDot(token css.Token) bool {
	return token.TokenType == css.DelimToken && string(token.Data) == "."
}

func newCSSTokenStreamRewriter(mapper *cssClassMapper) *cssTokenStreamRewriter {
	return &cssTokenStreamRewriter{
		mapper: mapper,
	}
}

func (rewriter *cssTokenStreamRewriter) write(
	builder *strings.Builder,
	tokenType css.TokenType,
	data []byte,
) {
	if rewriter.pendingClassDot {
		if tokenType == css.IdentToken {
			class := rewriter.mapper.classFor(string(data))
			builder.WriteByte('.')
			builder.WriteString(class.Generated)
			rewriter.pendingClassDot = false
			return
		}
		builder.WriteByte('.')
		rewriter.pendingClassDot = false
	}
	if tokenType == css.DelimToken && string(data) == "." {
		rewriter.pendingClassDot = true
		return
	}
	builder.Write(data)
}

func (rewriter *cssTokenStreamRewriter) flush(builder *strings.Builder) {
	if !rewriter.pendingClassDot {
		return
	}
	builder.WriteByte('.')
	rewriter.pendingClassDot = false
}

func newGeneratedClassAllocator() *generatedClassAllocator {
	return &generatedClassAllocator{
		used: map[string]string{},
	}
}

func (allocator *generatedClassAllocator) className(
	layout projectlayout.ProjectLayout,
	filePath string,
	className string,
) string {
	if allocator == nil {
		allocator = newGeneratedClassAllocator()
	}
	key := generatedClassKey(layout, filePath, className)
	base := hashedGeneratedClassName(key)
	candidate := base
	for suffix := 2; ; suffix++ {
		owner, ok := allocator.used[candidate]
		if !ok || owner == key {
			allocator.used[candidate] = key
			return candidate
		}
		candidate = base + "_" + strconv.Itoa(suffix)
	}
}

func newCSSClassMapper(
	layout projectlayout.ProjectLayout,
	filePath string,
	allocator *generatedClassAllocator,
) *cssClassMapper {
	return &cssClassMapper{
		layout:     layout,
		filePath:   filePath,
		allocator:  allocator,
		filePrefix: pascalIdentifier(strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))),
		seen:       map[string]cssClass{},
		constants:  map[string]int{},
	}
}

func (mapper *cssClassMapper) classFor(className string) cssClass {
	if class, ok := mapper.seen[className]; ok {
		return class
	}
	constant := mapper.filePrefix + pascalIdentifier(className) + "Class"
	if count := mapper.constants[constant]; count > 0 {
		constant = constant + strconv.Itoa(count+1)
	}
	mapper.constants[constant]++
	class := cssClass{
		Original:  className,
		Constant:  constant,
		Generated: mapper.allocator.className(mapper.layout, mapper.filePath, className),
	}
	mapper.seen[className] = class
	return class
}

func (mapper *cssClassMapper) classes() []cssClass {
	classNames := make([]string, 0, len(mapper.seen))
	for className := range mapper.seen {
		classNames = append(classNames, className)
	}
	sort.Strings(classNames)
	classes := make([]cssClass, 0, len(classNames))
	for _, className := range classNames {
		classes = append(classes, mapper.seen[className])
	}
	return classes
}

func buildRouteBundle(
	layout projectlayout.ProjectLayout,
	index *assetIndex,
	route RouteSpec,
) (*routeBundle, []*cssBundle, error) {
	collector := newDependencyCollector(layout, index)
	for _, templatePath := range route.TemplatePaths {
		collector.addFile(templatePath)
	}

	cssSpecs := route.CSSBundles
	if len(cssSpecs) == 0 {
		cssSpecs = fallbackCSSBundleSpecs(route)
	}

	cssBundles := make([]*cssBundle, 0, len(cssSpecs))
	cssBundlePaths := make([]string, 0, len(cssSpecs))
	seenBundlePaths := map[string]struct{}{}
	for _, spec := range cssSpecs {
		assetPath, err := cssBundleAssetPath(layout, spec)
		if err != nil {
			return nil, nil, err
		}
		if _, ok := seenBundlePaths[assetPath]; !ok {
			seenBundlePaths[assetPath] = struct{}{}
			cssBundlePaths = append(cssBundlePaths, assetPath)
		}
		cssBundles = append(cssBundles, &cssBundle{
			AssetPath: assetPath,
			CSSFiles:  collectCSSBundleAssets(layout, index, spec.TemplatePaths),
		})
	}

	return &routeBundle{
		RouteID:        route.RouteID,
		CSSBundlePaths: cssBundlePaths,
		ScriptFiles:    sortedScriptAssets(collector.scripts),
	}, cssBundles, nil
}

func bundleClientAssetsByRoute(
	bundles map[string]*routeBundle,
	cssBundlesByPath map[string]*cssBundle,
) map[string]metagen.ClientAssets {
	assetsByRoute := make(map[string]metagen.ClientAssets, len(bundles))
	for routeID, bundle := range bundles {
		assetsByRoute[routeID] = bundleClientAssets(bundle, cssBundlesByPath)
	}
	return assetsByRoute
}

func bundleClientAssets(bundle *routeBundle, cssBundlesByPath map[string]*cssBundle) metagen.ClientAssets {
	assets := metagen.ClientAssets{}
	for _, assetPath := range bundle.CSSBundlePaths {
		cssBundle := cssBundlesByPath[assetPath]
		if cssBundle == nil || len(cssBundle.CSSFiles) == 0 {
			continue
		}
		assets.Stylesheets = append(assets.Stylesheets, assetPath)
	}
	for _, file := range bundle.ScriptFiles {
		assets.ModuleScripts = append(assets.ModuleScripts, file.AssetPath)
	}
	return assets
}

func fallbackCSSBundleSpecs(route RouteSpec) []CSSBundleSpec {
	specs := make([]CSSBundleSpec, 0, len(route.TemplatePaths))
	for _, templatePath := range route.TemplatePaths {
		if strings.TrimSpace(templatePath) == "" {
			continue
		}
		specs = append(specs, CSSBundleSpec{
			OwnerTemplatePath: templatePath,
			TemplatePaths:     []string{templatePath},
		})
	}
	return specs
}

func cssBundleAssetPath(layout projectlayout.ProjectLayout, spec CSSBundleSpec) (string, error) {
	ownerPath := strings.TrimSpace(spec.OwnerTemplatePath)
	if ownerPath == "" {
		return "", fmt.Errorf("css bundle owner template path is required")
	}
	return logicalCSSAssetPath(layout, ownerPath)
}

func collectCSSBundleAssets(
	layout projectlayout.ProjectLayout,
	index *assetIndex,
	templatePaths []string,
) []*cssAsset {
	files := []*cssAsset{}
	seen := map[*cssAsset]struct{}{}
	for _, templatePath := range templatePaths {
		collector := newDependencyCollector(layout, index)
		collector.addFile(templatePath)
		for _, css := range nonEmptyCSSAssets(sortedCSSAssets(collector.css)) {
			if _, ok := seen[css]; ok {
				continue
			}
			seen[css] = struct{}{}
			files = append(files, css)
		}
	}
	return files
}

func mergeCSSBundles(
	bundlesByPath map[string]*cssBundle,
	bundleOrder *[]string,
	bundles []*cssBundle,
) {
	for _, bundle := range bundles {
		if bundle == nil || strings.TrimSpace(bundle.AssetPath) == "" {
			continue
		}
		existing := bundlesByPath[bundle.AssetPath]
		if existing == nil {
			existing = &cssBundle{AssetPath: bundle.AssetPath}
			bundlesByPath[bundle.AssetPath] = existing
			*bundleOrder = append(*bundleOrder, bundle.AssetPath)
		}
		appendUniqueCSSAssets(&existing.CSSFiles, bundle.CSSFiles)
	}
}

func appendUniqueCSSAssets(target *[]*cssAsset, files []*cssAsset) {
	seen := map[*cssAsset]struct{}{}
	for _, file := range *target {
		seen[file] = struct{}{}
	}
	for _, file := range files {
		if file == nil {
			continue
		}
		if _, ok := seen[file]; ok {
			continue
		}
		seen[file] = struct{}{}
		*target = append(*target, file)
	}
}

type dependencyCollector struct {
	layout       projectlayout.ProjectLayout
	index        *assetIndex
	visitedFiles map[string]struct{}
	visitedDirs  map[string]struct{}
	css          map[*cssAsset]struct{}
	scripts      map[*scriptAsset]struct{}
}

func newDependencyCollector(layout projectlayout.ProjectLayout, index *assetIndex) *dependencyCollector {
	return &dependencyCollector{
		layout:       layout,
		index:        index,
		visitedFiles: map[string]struct{}{},
		visitedDirs:  map[string]struct{}{},
		css:          map[*cssAsset]struct{}{},
		scripts:      map[*scriptAsset]struct{}{},
	}
}

func (collector *dependencyCollector) addFile(filePath string) {
	cleanPath := filepath.Clean(filePath)
	if _, ok := collector.visitedFiles[cleanPath]; ok {
		return
	}
	collector.visitedFiles[cleanPath] = struct{}{}
	collector.addFileAssets(cleanPath)

	content, err := os.ReadFile(cleanPath)
	if err != nil {
		return
	}
	for _, importPath := range quotedImports(string(content)) {
		if dir, ok := collector.componentDirForImport(importPath); ok {
			collector.addDir(dir)
			collector.scanPackageFiles(dir)
		}
	}
}

func (collector *dependencyCollector) addFileAssets(filePath string) {
	stem := strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
	if stem == "" {
		return
	}

	dir := filepath.Dir(filepath.Clean(filePath))
	for _, asset := range collector.index.cssByDir[dir] {
		if assetStem(asset.SourcePath) == stem {
			collector.css[asset] = struct{}{}
		}
	}
	if stem == "root" {
		return
	}
	for _, asset := range collector.index.scriptByDir[dir] {
		if assetStem(asset.SourcePath) == stem {
			collector.scripts[asset] = struct{}{}
		}
	}
}

func (collector *dependencyCollector) addDir(dir string) {
	cleanDir := filepath.Clean(dir)
	if _, ok := collector.visitedDirs[cleanDir]; ok {
		return
	}
	collector.visitedDirs[cleanDir] = struct{}{}
	for _, asset := range collector.index.cssByDir[cleanDir] {
		collector.css[asset] = struct{}{}
	}
	for _, asset := range collector.index.scriptByDir[cleanDir] {
		collector.scripts[asset] = struct{}{}
	}
}

func (collector *dependencyCollector) scanPackageFiles(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) != ".templ" && filepath.Ext(name) != ".go" {
			continue
		}
		if strings.HasSuffix(name, "_test.go") || isGeneratedHelper(name) {
			continue
		}
		collector.addFile(filepath.Join(dir, name))
	}
}

func (collector *dependencyCollector) componentDirForImport(importPath string) (string, bool) {
	prefix := path.Join(collector.layout.AppModulePath, componentsImportPath(collector.layout))
	trimmed := strings.TrimSpace(importPath)
	if trimmed != prefix && !strings.HasPrefix(trimmed, prefix+"/") {
		return "", false
	}
	relative := strings.TrimPrefix(trimmed, prefix)
	relative = strings.TrimPrefix(relative, "/")
	return filepath.Join(componentsDir(collector.layout), filepath.FromSlash(relative)), true
}

func DiscoverRouteSpecs(layout projectlayout.ProjectLayout) ([]RouteSpec, error) {
	discovery, err := discoverRouteAssets(layout)
	if err != nil {
		return nil, err
	}

	routeIDs := make([]string, 0, len(discovery.pages))
	for routeID := range discovery.pages {
		if isSlotRouteID(routeID) {
			continue
		}
		routeIDs = append(routeIDs, routeID)
	}
	sort.Strings(routeIDs)

	routes := make([]RouteSpec, 0, len(routeIDs))
	for _, routeID := range routeIDs {
		templates, cssBundles := clientAssetTemplatesForRoute(
			discovery.rootTemplate,
			routeID,
			discovery.layoutByRoute,
			discovery.slotTemplatesByOwner,
			discovery.pages[routeID],
		)
		routes = append(routes, RouteSpec{
			RouteID:       routeID,
			TemplatePaths: templates,
			CSSBundles:    cssBundles,
		})
	}
	return routes, nil
}

func DiscoverNotFoundSpecs(layout projectlayout.ProjectLayout) ([]RouteSpec, error) {
	discovery, err := discoverRouteAssets(layout)
	if err != nil {
		return nil, err
	}

	routeIDs := make([]string, 0, len(discovery.notFounds))
	for routeID := range discovery.notFounds {
		if isSlotRouteID(routeID) {
			continue
		}
		routeIDs = append(routeIDs, routeID)
	}
	sort.Strings(routeIDs)

	routes := make([]RouteSpec, 0, len(routeIDs))
	for _, routeID := range routeIDs {
		templates, cssBundles := clientAssetTemplatesForRoute(
			discovery.rootTemplate,
			routeID,
			discovery.layoutByRoute,
			discovery.slotTemplatesByOwner,
			discovery.notFounds[routeID],
		)
		routes = append(routes, RouteSpec{
			RouteID:       routeID,
			TemplatePaths: templates,
			CSSBundles:    cssBundles,
		})
	}
	return routes, nil
}

type routeAssetDiscovery struct {
	rootTemplate         string
	layoutByRoute        map[string]string
	pages                map[string]string
	notFounds            map[string]string
	slotTemplatesByOwner map[string][]string
}

type routeTemplateRef struct {
	RouteID    string
	SourcePath string
}

func discoverRouteAssets(layout projectlayout.ProjectLayout) (*routeAssetDiscovery, error) {
	root := strings.TrimSpace(layout.RoutesDir)
	if root == "" {
		return nil, fmt.Errorf("routes dir is required")
	}
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return &routeAssetDiscovery{
				layoutByRoute:        map[string]string{},
				pages:                map[string]string{},
				notFounds:            map[string]string{},
				slotTemplatesByOwner: map[string][]string{},
			}, nil
		}
		return nil, err
	}

	discovery := &routeAssetDiscovery{
		layoutByRoute:        map[string]string{},
		pages:                map[string]string{},
		notFounds:            map[string]string{},
		slotTemplatesByOwner: map[string][]string{},
	}
	if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		name := entry.Name()
		switch name {
		case "root.templ", "layout.templ", "page.templ", "default.templ", "404.templ":
		default:
			return nil
		}

		dir := filepath.Dir(filePath)
		routeID, err := routeIDForDir(root, dir)
		if err != nil {
			return err
		}
		if ownerRouteID, ok, err := slotOwnerRouteID(root, dir); err != nil {
			return err
		} else if ok {
			discovery.slotTemplatesByOwner[ownerRouteID] = append(
				discovery.slotTemplatesByOwner[ownerRouteID],
				filePath,
			)
		}

		switch name {
		case "root.templ":
			discovery.rootTemplate = filePath
		case "layout.templ":
			discovery.layoutByRoute[routeID] = filePath
		case "page.templ":
			discovery.pages[routeID] = filePath
		case "404.templ":
			discovery.notFounds[routeID] = filePath
		}
		return nil
	}); err != nil {
		return nil, err
	}

	for ownerRouteID := range discovery.slotTemplatesByOwner {
		sort.Strings(discovery.slotTemplatesByOwner[ownerRouteID])
	}
	return discovery, nil
}

func clientAssetTemplatesForRoute(
	rootTemplate string,
	routeID string,
	layoutByRoute map[string]string,
	slotTemplatesByOwner map[string][]string,
	terminalTemplate string,
) ([]string, []CSSBundleSpec) {
	templates := []string{}
	seenTemplates := map[string]struct{}{}
	cssBundles := []CSSBundleSpec{}

	if strings.TrimSpace(rootTemplate) != "" {
		appendUniquePath(&templates, seenTemplates, rootTemplate)
		cssBundles = append(cssBundles, CSSBundleSpec{
			OwnerTemplatePath: rootTemplate,
			TemplatePaths:     []string{rootTemplate},
		})
	}

	layoutRefs := layoutTemplateChain(routeID, layoutByRoute)
	lastNonRootLayout := -1
	for _, layout := range layoutRefs {
		appendUniquePath(&templates, seenTemplates, layout.SourcePath)
		bundlePaths := []string{layout.SourcePath}
		for _, slotTemplate := range slotTemplatesByOwner[layout.RouteID] {
			appendUniquePath(&templates, seenTemplates, slotTemplate)
			bundlePaths = append(bundlePaths, slotTemplate)
		}
		if layout.RouteID != "" {
			lastNonRootLayout = len(cssBundles)
		}
		cssBundles = append(cssBundles, CSSBundleSpec{
			OwnerTemplatePath: layout.SourcePath,
			TemplatePaths:     bundlePaths,
		})
	}

	if strings.TrimSpace(terminalTemplate) != "" {
		appendUniquePath(&templates, seenTemplates, terminalTemplate)
		if lastNonRootLayout >= 0 {
			cssBundles[lastNonRootLayout].TemplatePaths = append(
				cssBundles[lastNonRootLayout].TemplatePaths,
				terminalTemplate,
			)
		} else {
			cssBundles = append(cssBundles, CSSBundleSpec{
				OwnerTemplatePath: terminalTemplate,
				TemplatePaths:     []string{terminalTemplate},
			})
		}
	}

	return templates, cssBundles
}

func appendUniquePath(paths *[]string, seen map[string]struct{}, filePath string) {
	if strings.TrimSpace(filePath) == "" {
		return
	}
	if _, ok := seen[filePath]; ok {
		return
	}
	seen[filePath] = struct{}{}
	*paths = append(*paths, filePath)
}

func layoutTemplateChain(routeID string, layoutByRoute map[string]string) []routeTemplateRef {
	segments := []string{}
	if strings.TrimSpace(routeID) != "" {
		segments = strings.Split(routeID, "/")
	}
	candidates := []string{""}
	for idx := 1; idx <= len(segments); idx++ {
		candidates = append(candidates, strings.Join(segments[:idx], "/"))
	}
	refs := make([]routeTemplateRef, 0, len(candidates))
	for _, candidate := range candidates {
		if filePath := layoutByRoute[candidate]; strings.TrimSpace(filePath) != "" {
			refs = append(refs, routeTemplateRef{RouteID: candidate, SourcePath: filePath})
		}
	}
	return refs
}

func slotOwnerRouteID(root string, dir string) (string, bool, error) {
	relative, err := filepath.Rel(root, dir)
	if err != nil {
		return "", false, err
	}
	relative = filepath.ToSlash(relative)
	if relative == "." {
		return "", false, nil
	}
	segments := strings.Split(relative, "/")
	for index, segment := range segments {
		if !strings.HasPrefix(segment, "_slot__") {
			continue
		}
		ownerDir := root
		if index > 0 {
			ownerDir = filepath.Join(root, filepath.FromSlash(strings.Join(segments[:index], "/")))
		}
		ownerRouteID, err := routeIDForDir(root, ownerDir)
		if err != nil {
			return "", false, err
		}
		return ownerRouteID, true, nil
	}
	return "", false, nil
}

func isSlotRouteID(routeID string) bool {
	for _, segment := range strings.Split(routeID, "/") {
		if strings.HasPrefix(segment, "_slot__") {
			return true
		}
	}
	return false
}

func routeIDForDir(root string, dir string) (string, error) {
	relative, err := filepath.Rel(root, dir)
	if err != nil {
		return "", err
	}
	relative = filepath.ToSlash(relative)
	if relative == "." {
		relative = ""
	}
	rawSegments, err := frameworkrouter.ParseDirectorySegments(relative)
	if err != nil {
		return "", err
	}
	parts := make([]string, 0, len(rawSegments))
	for _, segment := range rawSegments {
		parts = append(parts, segment.RawPart())
	}
	return strings.Join(parts, "/"), nil
}

func writeStaticOutputs(stageDir string, layout projectlayout.ProjectLayout, plan Plan) error {
	for _, bundle := range plan.cssBundles {
		if err := writeCSSBundle(stageDir, bundle); err != nil {
			return err
		}
	}
	if err := writeScriptBundles(stageDir, layout, plan.scriptFiles); err != nil {
		return err
	}
	return nil
}

func writeCSSBundle(stageDir string, bundle *cssBundle) error {
	if bundle == nil || len(bundle.CSSFiles) == 0 {
		return nil
	}
	builder := strings.Builder{}
	for _, file := range bundle.CSSFiles {
		if file == nil || strings.TrimSpace(file.Transformed) == "" {
			continue
		}
		if builder.Len() > 0 {
			builder.WriteByte('\n')
		}
		builder.WriteString(file.Transformed)
		if !strings.HasSuffix(file.Transformed, "\n") {
			builder.WriteByte('\n')
		}
	}
	if strings.TrimSpace(builder.String()) == "" {
		return nil
	}
	return writeStageFile(stageDir, bundle.AssetPath, []byte(builder.String()))
}

func writeScriptBundles(stageDir string, layout projectlayout.ProjectLayout, files []*scriptAsset) error {
	if len(files) == 0 {
		return nil
	}
	entryPoints := make([]string, 0, len(files))
	assetPathOwners := map[string]string{}
	for _, file := range files {
		if file == nil {
			continue
		}
		assetPath := filepath.ToSlash(file.AssetPath)
		if existing, ok := assetPathOwners[assetPath]; ok {
			return fmt.Errorf("client script output %q is produced by both %q and %q", assetPath, existing, file.SourcePath)
		}
		assetPathOwners[assetPath] = file.SourcePath
		entryPoints = append(entryPoints, file.SourcePath)
	}
	if len(entryPoints) == 0 {
		return nil
	}

	webRoot := filepath.Dir(layout.RoutesDir)
	result := api.Build(api.BuildOptions{
		EntryPoints:       entryPoints,
		AbsWorkingDir:     layout.RootDir,
		Outdir:            stageDir,
		Outbase:           webRoot,
		EntryNames:        "[dir]/[name]",
		ChunkNames:        "chunks/[name]-[hash]",
		Bundle:            true,
		Write:             true,
		Format:            api.FormatESModule,
		Splitting:         true,
		Platform:          api.PlatformBrowser,
		Target:            api.ES2020,
		MinifyWhitespace:  true,
		MinifySyntax:      true,
		MinifyIdentifiers: true,
	})
	if len(result.Errors) > 0 {
		return fmt.Errorf("bundle client scripts: %s", result.Errors[0].Text)
	}
	return nil
}

func writeStageFile(stageDir string, assetPath string, content []byte) error {
	target := filepath.Join(stageDir, filepath.FromSlash(strings.TrimLeft(assetPath, "/")))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create asset dir for %q: %w", target, err)
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		return fmt.Errorf("write asset %q: %w", target, err)
	}
	return nil
}

func writeCSSHelper(asset *cssAsset) error {
	builder := strings.Builder{}
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage ")
	builder.WriteString(asset.PackageName)
	builder.WriteString("\n\n")
	if len(asset.Classes) > 0 {
		builder.WriteString("const (\n")
		for _, class := range asset.Classes {
			builder.WriteString("\t")
			builder.WriteString(class.Constant)
			builder.WriteString(" = ")
			builder.WriteString(strconv.Quote(class.Generated))
			builder.WriteString("\n")
		}
		builder.WriteString(")\n")
	}
	return os.WriteFile(asset.HelperPath, []byte(builder.String()), 0o644)
}

func writeScriptHelper(asset *scriptAsset) error {
	builder := strings.Builder{}
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage ")
	builder.WriteString(asset.PackageName)
	builder.WriteString(`

import (
	"context"
	"html"
	"io"

	"github.com/RevoTale/no-js/framework/metagen"
	"github.com/a-h/templ"
)

var `)
	builder.WriteString(asset.VarName)
	builder.WriteString(" = templ.NewOnceHandle(templ.WithComponent(templ.ComponentFunc(\n")
	builder.WriteString("\tfunc(ctx context.Context, w io.Writer) error {\n")
	builder.WriteString("\tsrc := metagen.AssetURL(ctx, ")
	builder.WriteString(strconv.Quote(asset.AssetPath))
	builder.WriteString(")\n")
	builder.WriteString("\tif src == \"\" {\n\t\treturn nil\n\t}\n")
	builder.WriteString("\t_, err := io.WriteString(w, `<script type=\"module\" src=\"`+\n")
	builder.WriteString("\t\thtml.EscapeString(src)+`\"></script>`)\n")
	builder.WriteString("\treturn err\n})))\n\n")
	builder.WriteString("func ")
	builder.WriteString(asset.FuncName)
	builder.WriteString("() templ.Component {\n\treturn ")
	builder.WriteString(asset.VarName)
	builder.WriteString(".Once()\n}\n")
	return os.WriteFile(asset.HelperPath, []byte(builder.String()), 0o644)
}

func packageNameForDir(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf("read package dir %q: %w", dir, err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) == ".templ" {
			files = append(files, filepath.Join(dir, name))
		}
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) != ".go" || strings.HasSuffix(name, "_test.go") || isGeneratedHelper(name) {
			continue
		}
		files = append(files, filepath.Join(dir, name))
	}
	for _, filePath := range files {
		content, readErr := os.ReadFile(filePath)
		if readErr != nil {
			return "", readErr
		}
		match := packageRE.FindSubmatch(content)
		if len(match) >= 2 {
			return string(match[1]), nil
		}
	}
	return "", fmt.Errorf("no Go package declaration found in %q", dir)
}

func cleanGeneratedHelpers(layout projectlayout.ProjectLayout) error {
	for _, root := range clientAssetRoots(layout) {
		if _, err := os.Stat(root); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return err
		}
		if err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			if !isGeneratedHelper(filePath) {
				return nil
			}
			content, readErr := os.ReadFile(filePath)
			if readErr != nil {
				return readErr
			}
			if strings.HasPrefix(string(content), generatedHeader) {
				return os.Remove(filePath)
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func clientAssetRoots(layout projectlayout.ProjectLayout) []string {
	roots := []string{}
	if strings.TrimSpace(layout.RoutesDir) != "" {
		roots = append(roots, layout.RoutesDir)
	}
	componentRoot := componentsDir(layout)
	if strings.TrimSpace(componentRoot) != "" {
		roots = append(roots, componentRoot)
	}
	return roots
}

func componentsDir(layout projectlayout.ProjectLayout) string {
	if strings.TrimSpace(layout.RoutesDir) == "" {
		return ""
	}
	return filepath.Join(filepath.Dir(layout.RoutesDir), "components")
}

func componentsImportPath(layout projectlayout.ProjectLayout) string {
	routesImport := strings.Trim(strings.TrimSpace(layout.RoutesImport), "/")
	if routesImport == "" {
		return "components"
	}
	return path.Join(path.Dir(routesImport), "components")
}

func logicalCSSAssetPath(layout projectlayout.ProjectLayout, filePath string) (string, error) {
	return logicalAssetPath(layout, filePath, ".css")
}

func logicalScriptAssetPath(layout projectlayout.ProjectLayout, filePath string) (string, error) {
	return logicalAssetPath(layout, filePath, ".js")
}

func logicalAssetPath(layout projectlayout.ProjectLayout, filePath string, outputExt string) (string, error) {
	webRoot := filepath.Dir(layout.RoutesDir)
	relative, err := filepath.Rel(webRoot, filePath)
	if err != nil || strings.HasPrefix(relative, "..") {
		relative, err = filepath.Rel(layout.RootDir, filePath)
		if err != nil {
			return "", err
		}
	}
	relative = filepath.ToSlash(relative)
	ext := path.Ext(relative)
	return strings.TrimSuffix(relative, ext) + outputExt, nil
}

func quotedImports(content string) []string {
	matches := quotedImportRE.FindAllStringSubmatch(content, -1)
	imports := make([]string, 0, len(matches))
	for _, match := range matches {
		if len(match) >= 2 {
			imports = append(imports, strings.TrimSpace(match[1]))
		}
	}
	return imports
}

func nonEmptyCSSAssets(files []*cssAsset) []*cssAsset {
	out := make([]*cssAsset, 0, len(files))
	for _, file := range files {
		if file == nil || strings.TrimSpace(file.Transformed) == "" {
			continue
		}
		out = append(out, file)
	}
	return out
}

func sortedCSSAssets(values map[*cssAsset]struct{}) []*cssAsset {
	out := make([]*cssAsset, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Slice(out, func(i int, j int) bool { return out[i].SourcePath < out[j].SourcePath })
	return out
}

func sortedScriptAssets(values map[*scriptAsset]struct{}) []*scriptAsset {
	out := make([]*scriptAsset, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Slice(out, func(i int, j int) bool { return out[i].SourcePath < out[j].SourcePath })
	return out
}

func assetStem(filePath string) string {
	return strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
}

func generatedClassKey(layout projectlayout.ProjectLayout, filePath string, className string) string {
	relative, err := filepath.Rel(layout.RootDir, filePath)
	if err != nil {
		relative = filePath
	}
	return filepath.ToSlash(relative) + "\x00" + className
}

func hashedGeneratedClassName(key string) string {
	hash := sha1.Sum([]byte(key))
	encoded := hex.EncodeToString(hash[:])
	return "n_" + encoded[:8]
}

func pascalIdentifier(value string) string {
	builder := strings.Builder{}
	capitalize := true
	for _, r := range value {
		if r == '-' || r == '_' || r == '.' || r == ' ' {
			capitalize = true
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			capitalize = true
			continue
		}
		if builder.Len() == 0 && unicode.IsDigit(r) {
			builder.WriteString("X")
		}
		if capitalize {
			builder.WriteRune(unicode.ToUpper(r))
			capitalize = false
		} else {
			builder.WriteRune(r)
		}
	}
	if builder.Len() == 0 {
		return "Asset"
	}
	return builder.String()
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	r, size := utf8.DecodeRuneInString(value)
	if r == utf8.RuneError && size == 0 {
		return value
	}
	return string(unicode.ToLower(r)) + value[size:]
}

func shouldSkipDir(dir string, layout projectlayout.ProjectLayout) bool {
	clean := filepath.Clean(dir)
	for _, skip := range []string{layout.GeneratedDir, layout.StaticAssets.OutDir, layout.StaticAssets.SourceDir} {
		if strings.TrimSpace(skip) == "" {
			continue
		}
		if clean == filepath.Clean(skip) {
			return true
		}
	}
	base := filepath.Base(clean)
	return strings.HasPrefix(base, ".") || base == "node_modules"
}

func isCSSFile(filePath string) bool {
	return clientassetext.IsCSSFile(filePath)
}

func isScriptFile(filePath string) bool {
	return clientassetext.IsScriptFile(filePath)
}

func isGeneratedHelper(filePath string) bool {
	return clientassetext.IsGeneratedHelperName(filepath.Base(filePath))
}

func isSkipAll(err error) bool {
	return err == fs.SkipAll
}
