package i18ngen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	frameworki18n "github.com/RevoTale/no-js/framework/i18n"
	"github.com/RevoTale/no-js/internal/bundler/i18nkeygen"
	"github.com/RevoTale/no-js/internal/projectlayout"
)

const generatedHeader = "// Code generated by cmd/no-js. DO NOT EDIT."

type Config struct {
	Layout projectlayout.ProjectLayout
}

func Run(cfg Config) error {
	layout := cfg.Layout
	keysPath := filepath.Join(layout.GeneratedDir, "i18n", "keys_gen.go")
	messagesPath := filepath.Join(layout.GeneratedDir, "i18n", "messages", "bundle_gen.go")

	if !layout.BuiltInI18n.Enabled {
		if err := writeGeneratedFile(keysPath, generateEmptyKeysSource()); err != nil {
			return fmt.Errorf("write empty i18n keys: %w", err)
		}
		if err := writeGeneratedFile(messagesPath, generateEmptyMessagesSource(layout)); err != nil {
			return fmt.Errorf("write empty i18n runtime bundle: %w", err)
		}
		return nil
	}

	if strings.TrimSpace(layout.I18nDir) == "" {
		return fmt.Errorf("project layout i18n dir is required for built-in i18n generation")
	}

	messageFS := os.DirFS(layout.I18nDir)
	messageFiles, err := frameworki18n.DiscoverMessageFiles(messageFS)
	if err != nil {
		return fmt.Errorf("discover built-in i18n messages: %w", err)
	}

	localeMessages, canonicalLocale, err := frameworki18n.LoadMessageDefinitions(messageFS, messageFiles, "")
	if err != nil {
		return fmt.Errorf("load built-in i18n messages: %w", err)
	}

	canonicalMessages := localeMessages[canonicalLocale]
	if len(canonicalMessages) == 0 {
		return fmt.Errorf("canonical locale %q has no messages", canonicalLocale)
	}

	expectedKeys := make([]string, 0, len(canonicalMessages))
	for _, message := range canonicalMessages {
		expectedKeys = append(expectedKeys, message.ID)
	}
	if err := frameworki18n.ValidateMessageCatalog(messageFS, messageFiles, canonicalLocale, expectedKeys); err != nil {
		return fmt.Errorf("validate built-in i18n messages: %w", err)
	}

	keyDefs, err := i18nkeygen.BuildKeyDefs(canonicalMessages)
	if err != nil {
		return fmt.Errorf("build i18n key definitions: %w", err)
	}

	keysSource, err := i18nkeygen.GenerateFile("i18n", keyDefs)
	if err != nil {
		return fmt.Errorf("generate i18n keys source: %w", err)
	}
	messagesSource, err := generateMessagesSource(layout, keyDefs, localeMessages)
	if err != nil {
		return fmt.Errorf("generate i18n messages source: %w", err)
	}

	if err := writeGeneratedFile(keysPath, keysSource); err != nil {
		return fmt.Errorf("write i18n keys source: %w", err)
	}
	if err := writeGeneratedFile(messagesPath, messagesSource); err != nil {
		return fmt.Errorf("write i18n messages source: %w", err)
	}

	return nil
}

func writeGeneratedFile(targetPath string, source []byte) error {
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(targetPath, source, 0o644)
}

func generateEmptyKeysSource() []byte {
	const source = `// Code generated by cmd/no-js. DO NOT EDIT.
package i18n

type Key string

var Keys = []Key{}
`

	return []byte(source)
}

func generateEmptyMessagesSource(layout projectlayout.ProjectLayout) []byte {
	var buffer bytes.Buffer
	buffer.WriteString(generatedHeader + "\n")
	buffer.WriteString("package messages\n\n")
	buffer.WriteString("import (\n")
	fmt.Fprintf(&buffer, "\ti18n %q\n", generatedI18nImportPath(layout))
	fmt.Fprintf(&buffer, "\tframeworki18n %q\n", frameworkI18nImportPath())
	buffer.WriteString("\t\"net/http\"\n")
	buffer.WriteString("\t\"net/url\"\n")
	buffer.WriteString(")\n\n")
	buffer.WriteString("var zeroRuntime *frameworki18n.Runtime[i18n.Key]\n\n")
	buffer.WriteString("func Config() frameworki18n.Config {\n")
	buffer.WriteString("\treturn frameworki18n.Config{}\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("func NewContext(r *http.Request, root *url.URL) frameworki18n.Context[i18n.Key] {\n")
	buffer.WriteString("\treturn zeroRuntime.Context(r, root)\n")
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return buffer.Bytes()
	}
	return formatted
}

func generateMessagesSource(
	layout projectlayout.ProjectLayout,
	keyDefs []i18nkeygen.KeyDef,
	localeMessages map[string][]frameworki18n.Message,
) ([]byte, error) {
	defByID := make(map[string]i18nkeygen.KeyDef, len(keyDefs))
	for _, def := range keyDefs {
		defByID[def.ID] = def
	}

	locales := make([]string, 0, len(localeMessages))
	for locale := range localeMessages {
		locales = append(locales, locale)
	}
	sort.Strings(locales)

	var buffer bytes.Buffer
	buffer.WriteString(generatedHeader + "\n")
	buffer.WriteString("package messages\n\n")
	buffer.WriteString("import (\n")
	fmt.Fprintf(&buffer, "\ti18n %q\n", generatedI18nImportPath(layout))
	fmt.Fprintf(&buffer, "\twebi18n %q\n", appImportPath(layout.AppModulePath, strings.TrimSpace(layout.I18nImport)))
	fmt.Fprintf(&buffer, "\tframeworki18n %q\n", frameworkI18nImportPath())
	buffer.WriteString("\t\"net/http\"\n")
	buffer.WriteString("\t\"net/url\"\n")
	buffer.WriteString(")\n\n")
	buffer.WriteString("var defaultMessages = map[i18n.Key]string{\n")
	for _, def := range keyDefs {
		fmt.Fprintf(&buffer, "\ti18n.%s: %q,\n", def.Name, def.Default)
	}
	buffer.WriteString("}\n\n")
	buffer.WriteString("var bundle = func() *frameworki18n.Bundle[i18n.Key] {\n")
	buffer.WriteString("\tbundle, err := frameworki18n.NewStaticBundle(\n")
	buffer.WriteString("\t\twebi18n.Config(),\n")
	buffer.WriteString("\t\tmap[string]map[i18n.Key]frameworki18n.CompiledMessage{\n")
	for _, locale := range locales {
		fmt.Fprintf(&buffer, "\t\t\t%q: {\n", locale)
		messages := append([]frameworki18n.Message(nil), localeMessages[locale]...)
		sort.Slice(messages, func(i int, j int) bool { return messages[i].ID < messages[j].ID })
		for _, message := range messages {
			def, ok := defByID[message.ID]
			if !ok {
				return nil, fmt.Errorf("missing key definition for message %q", message.ID)
			}
			compiled, err := frameworki18n.CompileMessage(message.Translation)
			if err != nil {
				return nil, fmt.Errorf("compile message %q for locale %q: %w", message.ID, locale, err)
			}
			fmt.Fprintf(&buffer, "\t\t\t\ti18n.%s: {Parts: []frameworki18n.CompiledMessagePart{", def.Name)
			for _, part := range compiled.Parts {
				fmt.Fprintf(&buffer, "{Text: %q, Arg: %q},", part.Text, part.Arg)
			}
			buffer.WriteString("}},\n")
		}
		buffer.WriteString("\t\t\t},\n")
	}
	buffer.WriteString("\t\t},\n")
	buffer.WriteString("\t\tdefaultMessages,\n")
	buffer.WriteString("\t)\n")
	buffer.WriteString("\tif err != nil {\n")
	buffer.WriteString("\t\tpanic(err)\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn bundle\n")
	buffer.WriteString("}()\n\n")
	buffer.WriteString("var zeroRuntime *frameworki18n.Runtime[i18n.Key]\n\n")
	buffer.WriteString("func Config() frameworki18n.Config {\n")
	buffer.WriteString("\tif bundle == nil {\n")
	buffer.WriteString("\t\treturn frameworki18n.Config{}\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn bundle.Config()\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("func NewContext(r *http.Request, root *url.URL) frameworki18n.Context[i18n.Key] {\n")
	buffer.WriteString("\tif bundle == nil {\n")
	buffer.WriteString("\t\treturn zeroRuntime.Context(r, root)\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn bundle.Context(r, root)\n")
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format i18n messages source: %w", err)
	}
	return formatted, nil
}

func generatedI18nImportPath(layout projectlayout.ProjectLayout) string {
	return appImportPath(layout.AppModulePath, path.Join(strings.TrimSpace(layout.GeneratedImport), "i18n"))
}

func frameworkI18nImportPath() string {
	return "github.com/RevoTale/no-js/framework/i18n"
}

func appImportPath(modulePath string, relativePath string) string {
	trimmedModulePath := strings.TrimSpace(modulePath)
	trimmedRelativePath := strings.Trim(strings.TrimSpace(relativePath), "/")
	if trimmedRelativePath == "" {
		return trimmedModulePath
	}
	return path.Join(trimmedModulePath, trimmedRelativePath)
}
