// Code generated by cmd/approutegen. DO NOT EDIT.
package resolvers

import (
	"context"
	"example.com/no-js-e2e/routepagecssapp/web/view"
	"github.com/RevoTale/no-js/framework"
	"github.com/RevoTale/no-js/framework/metagen"
	"net/http"
)

type RootParams struct {
}

type RouteResolver interface {
	MetaGenRootLayout(meta framework.MetaContext[*view.Context]) (metagen.Metadata, error)
	MetaGenRootPage(meta framework.MetaContext[*view.Context], params RootParams) (metagen.Metadata, error)
	ResolveRootPage(ctx context.Context, appCtx *view.Context, r *http.Request, params RootParams) (view.RootPageView, error)
}

type Resolver struct{}

var _ RouteResolver = (*Resolver)(nil)
