// Code generated by framework/cmd/approutegen. DO NOT EDIT.
package resolvers

import (
	"blog/framework/metagen"
	"blog/internal/web/appcore"
	"context"
	"net/http"
)

type RootParams struct {
}

type AuthorParamSlugParams struct {
	Slug string
}

type ChannelsParams struct {
}

type MicroTalesParams struct {
}

type NoteParamSlugParams struct {
	Slug string
}

type TagParamSlugParams struct {
	Slug string
}

type TalesParams struct {
}

type RouteResolver interface {
	MetaGenRootPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params RootParams) (metagen.Metadata, error)
	MetaGenAuthorParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params AuthorParamSlugParams) (metagen.Metadata, error)
	MetaGenChannelsPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params ChannelsParams) (metagen.Metadata, error)
	MetaGenMicroTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params MicroTalesParams) (metagen.Metadata, error)
	MetaGenNoteParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params NoteParamSlugParams) (metagen.Metadata, error)
	MetaGenTagParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TagParamSlugParams) (metagen.Metadata, error)
	MetaGenTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TalesParams) (metagen.Metadata, error)
	ResolveRootPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params RootParams) (appcore.NotesPageView, error)
	ResolveAuthorParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params AuthorParamSlugParams) (appcore.AuthorPageView, error)
	ResolveChannelsPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params ChannelsParams) (appcore.NotesPageView, error)
	ResolveMicroTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params MicroTalesParams) (appcore.NotesPageView, error)
	ResolveNoteParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params NoteParamSlugParams) (appcore.NotePageView, error)
	ResolveTagParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TagParamSlugParams) (appcore.NotesPageView, error)
	ResolveTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TalesParams) (appcore.NotesPageView, error)
}

type Resolver struct{}

var _ RouteResolver = (*Resolver)(nil)
