package i18nkeygen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	frameworki18n "github.com/RevoTale/no-js/framework/i18n"
)

const GeneratedHeader = "// Code generated by cmd/i18nkeygen. DO NOT EDIT."

type Message = frameworki18n.Message

type KeyDef struct {
	ID      string
	Name    string
	Default string
}

func BuildKeyDefs(messages []Message) ([]KeyDef, error) {
	if len(messages) == 0 {
		return nil, fmt.Errorf("messages are empty")
	}

	defs := make([]KeyDef, 0, len(messages))
	seenNames := make(map[string]string, len(messages))
	for _, msg := range messages {
		name := constNameForID(msg.ID)
		if name == "" {
			return nil, fmt.Errorf("message id %q cannot be converted to key constant name", msg.ID)
		}
		if existingID, exists := seenNames[name]; exists {
			return nil, fmt.Errorf(
				"message ids %q and %q collide to the same key constant %q",
				existingID,
				msg.ID,
				name,
			)
		}
		seenNames[name] = msg.ID
		defs = append(defs, KeyDef{
			ID:      msg.ID,
			Name:    name,
			Default: msg.Translation,
		})
	}

	sort.Slice(defs, func(i int, j int) bool {
		return defs[i].ID < defs[j].ID
	})
	return defs, nil
}

func GenerateFromJSON(packageName string, data []byte) ([]byte, error) {
	messages, err := frameworki18n.ParseCanonicalMessages(data)
	if err != nil {
		return nil, err
	}
	defs, err := BuildKeyDefs(messages)
	if err != nil {
		return nil, err
	}
	return GenerateFile(packageName, defs)
}

func GenerateFile(packageName string, defs []KeyDef) ([]byte, error) {
	packageName = strings.TrimSpace(packageName)
	if packageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if len(defs) == 0 {
		return nil, fmt.Errorf("key definitions are empty")
	}

	sortedDefs := make([]KeyDef, len(defs))
	copy(sortedDefs, defs)
	sort.Slice(sortedDefs, func(i int, j int) bool {
		return sortedDefs[i].ID < sortedDefs[j].ID
	})

	var buffer bytes.Buffer
	fmt.Fprintf(&buffer, "%s\n", GeneratedHeader)
	fmt.Fprintf(&buffer, "package %s\n\n", packageName)
	buffer.WriteString("type Key string\n\n")
	buffer.WriteString("const (\n")
	for _, def := range sortedDefs {
		fmt.Fprintf(&buffer, "\t%s Key = %q\n", def.Name, def.ID)
	}
	buffer.WriteString(")\n\n")

	buffer.WriteString("var AllKeys = []Key{\n")
	for _, def := range sortedDefs {
		fmt.Fprintf(&buffer, "\t%s,\n", def.Name)
	}
	buffer.WriteString("}\n\n")

	buffer.WriteString("var DefaultMessages = map[Key]string{\n")
	for _, def := range sortedDefs {
		fmt.Fprintf(&buffer, "\t%s: %q,\n", def.Name, def.Default)
	}
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func constNameForID(id string) string {
	id = strings.TrimSpace(id)
	if id == "" {
		return ""
	}

	parts := splitAlphaNumericParts(id)
	if len(parts) == 0 {
		return ""
	}

	var builder strings.Builder
	builder.WriteString("Key")
	for _, part := range parts {
		builder.WriteString(toPascalPreservingInnerCaps(part))
	}
	return builder.String()
}

func splitAlphaNumericParts(input string) []string {
	parts := make([]string, 0, 8)
	var current strings.Builder
	for _, r := range input {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			current.WriteRune(r)
			continue
		}
		if current.Len() > 0 {
			parts = append(parts, current.String())
			current.Reset()
		}
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	return parts
}

func toPascalPreservingInnerCaps(input string) string {
	if input == "" {
		return ""
	}
	segments := splitCamelLikeSegments(input)
	if len(segments) == 0 {
		return ""
	}

	var builder strings.Builder
	for _, segment := range segments {
		builder.WriteString(uppercaseFirst(segment))
	}
	return builder.String()
}

func splitCamelLikeSegments(input string) []string {
	runes := []rune(input)
	if len(runes) < 2 {
		return []string{input}
	}

	segments := make([]string, 0, 4)
	start := 0
	for index := 1; index < len(runes); index++ {
		prev := runes[index-1]
		current := runes[index]

		if unicode.IsUpper(current) && unicode.IsLower(prev) {
			segments = append(segments, string(runes[start:index]))
			start = index
			continue
		}

		if unicode.IsDigit(current) != unicode.IsDigit(prev) {
			segments = append(segments, string(runes[start:index]))
			start = index
		}
	}
	segments = append(segments, string(runes[start:]))
	return segments
}

func uppercaseFirst(input string) string {
	if input == "" {
		return ""
	}
	first, width := utf8.DecodeRuneInString(input)
	return string(unicode.ToUpper(first)) + input[width:]
}
